### ISSUE TITLE
Syntax on line 114 for Out-File

### ISSUE THREAD

**Issue by Geladekim** [bseltz-cohesity/scripts#10]
Line 114 should be using -Filepath rather than -File.

Not-working
$html | Out-File -File 'storageGrowth.html' -Encoding ascii

Working
$html | Out-File -Filepath 'storageGrowth.html' -Encoding ascii

**Comment by Geladekim** [comment]
My current powershell version is 5.1.14409.1018.

My apologies if the issue lies between my keyboard and chair.

Below are the results I received when attempting to use the -Path option.

Connected!
Gathering Storage Statistics...
Writing Output to C:\PSscripts\Cohesity\storageGrowth.html
Out-File : A parameter cannot be found that matches parameter name 'Path'.
At C:\PSscripts\Cohesity\storageChart.ps1:114 char:18
+ $html | Out-File -Path 'storageGrowth.html' -Encoding ascii
+                  ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.OutFileCommand

. : The term 'C:\PSscripts\Cohesity\storageGrowth.html' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At C:\PSscripts\Cohesity\storageChart.ps1:115 char:2
+ .$outFilePath
+  ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\PSscripts\Cohesity\storageGrowth.html:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bseltz-cohesity** [comment]
Ah I see now. It was -Path, not -File, and -Path works on OSX but not on Windows apparently. Fixed...

**Comment by Tha-Fox** [comment]
I'm not sure, where this is fixed. I just downloaded the file in here: 
https://github.com/bseltz-cohesity/scripts/blob/master/capacityTools/storageChart/storageChart.ps1

On line 114, there is still a parameter "-Path" and Powershell 5.1.18362.145 on Windows 10 doesn't recognize it. When I change it to "-FilePath", it works.

**Comment by bseltz-cohesity** [comment]
Sorry there's two copies of this script. I just fixed the one you're referring to. Thanks for reporting!
