### ISSUE TITLE
SQL and Oracle script to unprotect entire SQL or Oracle server in a Protection Group

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#102]
I'm looking for a script where a SQL server is setup as Auto-protected in a SQL -file-based Protection group and needs to be removed from the Protection group due to the server being decommissioned.   If there is anyway to get a powershell script created for this use case?

**Comment by amhaats1** [comment]
Also is it possible to do the same for a Oracle server, to unprotect the entire server in a Protection Group

**Comment by bseltz-cohesity** [comment]
For SQL: https://github.com/bseltz-cohesity/scripts/tree/master/sql/unprotectSQLServer
For Oracle: https://github.com/bseltz-cohesity/scripts/tree/master/oracle/powershell/unprotectOracleServer

**Comment by amhaats1** [comment]
Great thank you so much!! These are working great and will be great to use these scripts in our automated decommissioning process for servers.
