### ISSUE TITLE
Can file given to --metadatafile option of backupNow.py have mix of absolute path of dir and files?

### ISSUE THREAD

**Issue by nansari** [bseltz-cohesity/scripts#103]
Can file argument ( mymetafile.txt ) given to --metadatafile option of python/backupNow/backupNow.py have mix of absolute path of dir and files?

for example:

```
$ SCRIPTPATH="/opt/cohesity/agent/software/crux/bin/user_scripts"
$ cat mymetafile.txt
/dir1
/dir2/dir21
/dir3/file31
/dir3/file32
/dir4/dir41
/dir4/dir42/file421
$ ${SCRIPTPATH}/backupNow.py  --metadatafile mymetafile.txt <all_other_valid_options_here>
````

**Comment by bseltz-cohesity** [comment]
Yes you can have a mix of folders and files in the directive file. The Cohesity product documentation (https://docs.cohesity.com/6_6/Web/UserGuide/Content/Dashboard/Protection/JobServerPhysical_FileBased.htm#ProtectaPhysicalServerFilebased) provides examples that are mixed:

Entries in Windows directive file:
```
C:\Users
D:\Departments\Finance
D:\Departments\HR
G:\Misc\department_list.txt
G:\Misc_2\department_other_list.txt
```

Entries in Linux or UNIX Directive file
```
/home/cohesity/meta_file.txt
/home/cohesity/backup_folder
```
