### ISSUE TITLE
 Oracle DB in a Protection Group

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#104]
Sorry I should of asked for this in a previous issue I raised.

Is it possible to have a script to unprotect one/multiple oracle databases in a Protection Group also a script to protect one/multiple oracle databases in a Protection Group?

**Comment by bseltz-cohesity** [comment]
I have replaced the previous unprotectOracleServer script with this one, which can unprotect whole servers or individual databases: https://github.com/bseltz-cohesity/scripts/tree/master/oracle/powershell/unprotectOracle

**Comment by bseltz-cohesity** [comment]
I have also updated the protectOracle script to support protecting one or more (or all) DBs to a protection group: https://github.com/bseltz-cohesity/scripts/tree/master/oracle/powershell/protectOracle

**Comment by amhaats1** [comment]
This is working great, Thank you so much. Would you be able to do a Python version of the unprotectOracle? You already have a protectOracle out in https://github.com/bseltz-cohesity/scripts/tree/master/oracle/python that I could utilize.
I forget our database administrators are more familiar with Python scripts since our environment has Oracle on linux servers.

**Comment by bseltz-cohesity** [comment]
Yes I will work on the python versions next.

**Comment by bseltz-cohesity** [comment]
I have published unprotectOracle.py https://github.com/bseltz-cohesity/scripts/tree/master/oracle/python/unprotectOracle please let me know how it works for you
