### ISSUE TITLE
Grafana/Postgres credentials still good?

### ISSUE THREAD

**Issue by roxaskeyheart** [bseltz-cohesity/scripts#106]
I'm having trouble getting your Grafana panels to work, specifically around the datasource.

Following the instructions in the README, I can access the /irisservices/api/v1/public/postgres JSON which appears exactly as it should, but if I add these details to a datasource in Grafana, it will always timeout. I have confirmed there is no firewall in the way also.

Are these details/credentials still relevant for Cohesity 6.8.1_u3?

**Comment by bseltz-cohesity** [comment]
Yes the credentials are still valid but in 6.8.1_u3 the internal firewall in Cohesity defaults to deny for postgres access. In the Cohesity UI, go to Settings -> Networking -> Firewall and change the entry for "Reporting Database" to Allow

**Comment by roxaskeyheart** [comment]
I did this also, but still getting timeouts :(

**Comment by bseltz-cohesity** [comment]
You can also try to connect using the psql command line:
```psql --host=192.168.1.193 --port=27999 --username=reporting_read postgres
Password for user reporting_read: ***************
psql (13.2, server 10.22)
```
You might need to contact Cohesity support to help you troubleshoot
