### ISSUE TITLE
scripts/sql /aagFailoverMinder.ps1  - Possible to just refresh the source that has the error and run a Incremental on that source

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#107]
Is there a way this could be modified to just refresh the source that produced the error and run the Incremental backup on that source?

I have been testing this script and just seems to take a very long time to go through refreshing all the sources in the Protection Group and then running a Incremental. We have sometimes 10 plus servers in one Protection Group.  I'm thinking also it takes up more storage space if the incremental has to run for the entire Protection Group when its only needed for the source that failed.

**Comment by amhaats1** [comment]
Are you able to set the incremental job to run only on the failed source as well?

**Comment by bseltz-cohesity** [comment]
Yes that's what it does. It only runs the incremental backup for the affected database

**Comment by amhaats1** [comment]
Awesome, thank you,  it looks good on my end with my tests!
