### ISSUE TITLE
policyTool in PS and Python add and remove Quiet Times

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#109]
Would you be willing to update the policyTool to be able to add and remove Quiet Times?

The API references it as Blackout Window
Example:
            "blackoutWindow": [
              {
                "day": "Saturday",
                "startTime": {
                  "hour": 17,
                  "minute": 30
                },
                "endTime": {
                  "hour": 23,
                  "minute": 30
                }

**Comment by bseltz-cohesity** [comment]
Will do

**Comment by bseltz-cohesity** [comment]
I have updated policyTool.ps1. I added -addQuietTime and -removeQuietTime parameters, like: 
```
./policyTool.ps1 -vip mycluster -username myuser -policyName test -addQuietTime 'Monday,Friday,wednesday;04:00;04:30'
```
https://github.com/bseltz-cohesity/scripts/tree/master/powershell/policyTool

**Comment by bseltz-cohesity** [comment]
I have updated policyTool.py. I added -aq, --addquiettime and -rq, --removequiettime parameters like:
```
./policyTool.py -v mycluster -u myusername -p test -aq 'Wednesday;00:00;03:30'
```
