### ISSUE TITLE
Exclude list changed for all server in the protection job.

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#11]
We found this issue to be a major challenge. If you are adding new set of server to an **existing Protection job**,  which happens to have a different set of exclude this. then this script changes the exclude list of all the server in the protection Job which takes hours to redo !! This  is the Same case with protectAix.ps1 too.

Issue noticed and tested with protectPhysicalLinux.ps1 and protectAix.ps1

**Comment by bseltz-cohesity** [comment]
The script originally had the feature of keeping existing exclusions, but the customer I wrote this for wanted to overwrite them, so I removed it. I added a note in the readme about this for the linux and AIX versions of the script but it looks like I neglected to add that note to the Windows version. I will correct that. I will also consider how best to address the use case of adding without overwriting exclusions and let you know. Thanks for the feedback!

**Comment by RakeshMondalRon** [comment]
thank you very much for this quick response. The scrips have been very helpful.
 
I have a request with respect to addition of servers in AIX and LInux. By default Script adds the "/" filesystem to protection, But In some of the cases Customer only wishes to protect /var or /log from a server only via file-system. 
In such scenario we are unable to implement this script and adding 1000+ server that was is very painful, it is possible update the script to have that accommodated, to have custom path which we wish only to Protect ?

**Comment by bseltz-cohesity** [comment]
Sure I will work on a solution for this. Again, thanks for the feedback. It's very helpful to hear from customers about their real world use cases!

**Comment by bseltz-cohesity** [comment]
I have rewritten these scripts for windows: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/protectWindows and non-windows (Linux, AIX, Solaris): https://github.com/bseltz-cohesity/scripts/tree/master/powershell/protectLinux both will now avoid overwriting existing servers' includes and excludes unless explicitly requested. Also the non-windows version allows you to specify one or more include paths that and not just /.

**Comment by RakeshMondalRon** [comment]
We Tested the Scripts very same day. and it worked like a charm. Also i see there is no different script for AIX and Linux anymore. that is great.
