### ISSUE TITLE
ValidateVmBackups won't validate FreeBSD

### ISSUE THREAD

**Issue by pandaflourishingfish** [bseltz-cohesity/scripts#112]
I stumbled across this earlier this morning; it doesn't look like the "ValidateVMBackups" script will work with FreeBSD 13.x.  Originally I ran the validation against a pair of NetScalers, then had the same failure result when running against a vanilla FreeBSD install.  If it matters, it's Cohesity 6.8.1_u3 patch 11, vMware 7.0.3, and FreeBSD 13.2 running with ZFS. The status is "successful", but the validation is "false"

**Comment by bseltz-cohesity** [comment]
I don't have those OS's to test but if Cohesity doesn't support the file system formats or the way they are mounted, thus can't mount and browse the files, then no the script will not work.

**Comment by pandaflourishingfish** [comment]
I think you’re on to something.  I dug around in the docs and FreeBSD isn’t supported as a file system that can be indexed.  Interestingly, it does show as a supported guest OS on HyperV, but not on ESXi.

Thanks for the info



Carl Holzhauer, Managed Backup Sr
O 423-305-7890
 | D (423) 269-2543 | M 419-972-1295
***@***.***
1513 Cowart Street Chattanooga, TN 37408

​This electronic transmission and any attached documents or other writings are confidential and are for the sole use of the intended recipient(s) identified above. This message may contain information that is privileged, confidential or otherwise protected from disclosure under applicable law. If the receiver of this information is not the intended recipient, or the employee, or agent responsible for delivering the information to the intended recipient, you are hereby notified that any use, reading, dissemination, distribution, copying or storage of this information is strictly prohibited. If you have received this information in error, please notify the sender by return email and delete the electronic transmission, including all attachments from your system.
