### ISSUE TITLE
problem with DB restore from a tennant

### ISSUE THREAD

**Issue by HenrikFFM** [bseltz-cohesity/scripts#113]
Hi,

we have a 2 side Cohesity Cluster for a multi tennant environment. 

On Source Side i have a physical SQL Server cluster, which is in tennant 'Banking'.
We have registered the SQL Server cluster role as SQL Server datasource and as "Physical" datasource.
We take backups from the SQL Server datasource with cohesity frontend.

On the second site, which is the disaster recovery Site we need a regular restore of this backup.

The destination Server ('SQLDRVM005') is a VM from a large cluster. These cluster is not only for tennant 'Banking'.
We do a VM based backup of these cluster and his VMs.
In the tennant settings, i set the 'SQLDRVM005' as a member of tennant 'Banking'.
I change into the tennant and under sources i add SQL Server as an application for 'SQLDRVM005'.

Now i want to use the Scripts to restore on of the databases on 'SQLDRVM005'.
with restoreSQLps1 i get:
"The target host must be a Physical SQL host when restoring from file based SQL backups"

with cloneSQL the source Server wasnt found and -tennent is not allowed.

What can i do in this szenario?
i think, because these a community scripts no support is provided from cohesity so i cant open a case.

Greetings
Henrik

**Comment by bseltz-cohesity** [comment]
Hi @HenrikFFM you can not restore SQL backup from a SQL server registered as physical to a SQL server registered as a VM. You can only restore physical to physical or VM to VM. As for tenant support for the cloneSQL script, I will add a -tenant argument to the command line.
