### ISSUE TITLE
Unable to find cluster

### ISSUE THREAD

**Issue by pandaflourishingfish** [bseltz-cohesity/scripts#114]
I am trying to use the CloneVM script to clone a VM.  However, the script keeps complaining that it can't find the host/cluster I give it.  I've verified that the cluster name is valid by running "get-cluster" in PowerCLI and copy/pasting the name into the script. I've also tried with the name of a VMhost, but I get the same error.  I did verify that cloning a VM works in the GUI.  

![Capture](https://github.com/bseltz-cohesity/scripts/assets/138490770/0e0f42db-d910-4842-ad58-ebf45f2c7056)

**Comment by bseltz-cohesity** [comment]
I have validated that the script works as expected. The Datacenter names and Cluster names are visible in the UI when selecting a resource group
<img width="356" alt="Screenshot 2023-07-17 at 3 00 04 PM" src="https://github.com/bseltz-cohesity/scripts/assets/38843677/bcdcf0a8-73e6-4b8f-b55e-e0164dc0cba8">

**Comment by pandaflourishingfish** [comment]
It works for me in other sites without issue, this one is just proving to be...difficult.  I never thought of asking the Cohesity GUI for the values, thanks.

I did confirm they match though.

**Comment by bseltz-cohesity** [comment]
Try adding a line to the script, between lines 87 and 88:
```powershell
$resourcePoolId
```
then run the script and tell me if it displays a number or nothing or more than one number

**Comment by pandaflourishingfish** [comment]
Sorry for the delay, we ran that command and nothing changed, no output, just the same “host/cluster” not found



Carl Holzhauer, Managed Backup Sr
O 423-305-7890
 | D (423) 269-2543 | M 419-972-1295
***@***.***
1513 Cowart Street Chattanooga, TN 37408

​This electronic transmission and any attached documents or other writings are confidential and are for the sole use of the intended recipient(s) identified above. This message may contain information that is privileged, confidential or otherwise protected from disclosure under applicable law. If the receiver of this information is not the intended recipient, or the employee, or agent responsible for delivering the information to the intended recipient, you are hereby notified that any use, reading, dissemination, distribution, copying or storage of this information is strictly prohibited. If you have received this information in error, please notify the sender by return email and delete the electronic transmission, including all attachments from your system.

**Comment by bseltz-cohesity** [comment]
Fixed the issue with the cluster/host not found error due to unexpected sorting in object hierarchy
