### ISSUE TITLE
Support OTP code

### ISSUE THREAD

**Issue by mjamison7** [bseltz-cohesity/scripts#117]
I have used this script before and it works great.  I am in need of using it again but our Cohesity node now is using MFA and I need this script to support the OTP code.

This is the error I get now.

[13]:OTP code validation for user matthew failed with error: Invalid TOTP code for user matthew.
Not authenticated to a cohesity cluster

**Comment by bseltz-cohesity** [comment]
Sure I can add MFA support to any of the scripts. Please let me know which script you are referring to.

**Comment by mjamison7** [comment]
expireOldArchives.ps1 is the one that does not look like it has the MFA option.

**Comment by bseltz-cohesity** [comment]
Updated: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/expireOldArchives you can now specify `-mfaCode xxxxxx` on the command line

**Comment by mjamison7** [comment]
Thank you so much.  That is great!!!
