### ISSUE TITLE
sql/aagFailoverMinder/aagFailoverMinder.ps1 - kStale condition

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#119]
Can you help me with adding in this condition to your script?  I'm not seeing it execute correctly if it has a [kStale] condition,  Looks like the script is only looking for a kFailure condition

Here's how the failure comes out in our Alerts and in the Protection Group itself shows this error
Backup run of protection group NP_SQL_HA_RPO24H_31 of type kSQL failed with error [kStale]: Detected AAG metadata changes on the host for: CLSCMICRO4H

**Comment by bseltz-cohesity** [comment]
Hi I found an outdated run-now payload that I've now updated. Please get the latest version of the script here https://github.com/bseltz-cohesity/scripts/tree/master/sql/aagFailoverMinder and let me know if that solves the issue.

**Comment by amhaats1** [comment]
Thank you, we have implemented it in with our Non-Production SQL servers, I'll let you know how it goes.

**Comment by amhaats1** [comment]
It looks like the script isn't processing this condition correctly 'Discovered a break in the logchain',  It's not kicking off a Incremental backup with this occurs
Example
Backup task failed with error: [kSQLLogChainHoleFound]: [1-1-4] Discovered a break in the logchain for following databases: MSSQLSERVER/LMS_CAT, on Host WN3488.corp.mutualofomaha.com. Please make sure there is no other product backing up these databases.

**Comment by bseltz-cohesity** [comment]
Hi @amhaats1 can you open a support case with Cohesity so that we can converse in private. Thanks.
