### ISSUE TITLE
Not an Issue But a Request

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#12]
Hello Brian,

Apologies to create this as issue. But its more like a request disguised as suggestion. :)
Your scrips are working like wonder. and we have learned a lot.

Below are real scenarios from Production. ( and I am sure every organization would need them )

-We see scripts for adding , how do we remove Bulk clients from a policy ( A single policy )
-Is it possible to create a script which which checks the given list of object (servers) and output the list of ProtectionJobs its added to,  with corresponding include and exclude list. ?

Regards
Ron

**Comment by bseltz-cohesity** [comment]
Thanks for the suggestions Rakesh I will work on these

**Comment by bseltz-cohesity** [comment]
I have just published a script to report the paths included/excluded in physical file-based protection jobs: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/listProtectedFilePaths

**Comment by bseltz-cohesity** [comment]
I have just published a script to remove server(s) from physical file-based protection jobs: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/unprotectPhysicalServer
