### ISSUE TITLE
backupNow

### ISSUE THREAD

**Issue by geoffaskam** [bseltz-cohesity/scripts#121]
Hi Brian,
I'm getting the following message each time i execute the backupNow.py script, 

Connected!
Waiting for existing run to finish

I've tried adding the -cp 1 flag to try and stop previous runs but it still fails, any guidance would be appreciated?

**Comment by bseltz-cohesity** [comment]
Hi @geoffaskam 
Yes this issue appeared after applying patch 6.8.1 p11 or 6.6.0d p34. Please update to the latest version of backupNow.py and pyhesity.py:  https://github.com/bseltz-cohesity/scripts/tree/master/python/backupNow
https://github.com/bseltz-cohesity/scripts/tree/master/python/pyhesity

**Comment by geoffaskam** [comment]
Thanks Brian, all working fine now.
