### ISSUE TITLE
backupNow.ps1 - Null Array

### ISSUE THREAD

**Issue by Triggaa85** [bseltz-cohesity/scripts#123]
Using -objects results in this looping error.  Backup of the object is successful if I check he Cohesity portal.

```
Cannot index into a null array.
At \\\Cohesity\Powershell Scripts\backupNow.ps1:441 char:5
+     $newRunId = $runs[0].backupRun.jobRunId
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Comment by bseltz-cohesity** [comment]
You're apparently using a very old version of the script, please get the updated versions of these two files: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/backupNow and https://github.com/bseltz-cohesity/scripts/tree/master/powershell/cohesity-api

**Comment by Triggaa85** [comment]
You were right, I thought I'd updated. Apologies
