### ISSUE TITLE
Is it possible to add Taskname and text file to add all the VMs need to recover 

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#125]
Script : /scripts/master/python/recoverVMv2/recoverVMv2.py

I'm trying to use the recoverVMv2 and to enhance the script is it possible to add taskname and text file to add all the VMs need to recover instead of giving in the command line

**Comment by bseltz-cohesity** [comment]
Hi @Sheeba86 I have added a -taskName parameter to the script. The script already has a -vmList parameter that allows you to specify a text file of VMs to recover

**Comment by Sheeba86** [comment]
Hi Brian,

 Thanks I could see its been updated in the powershell script. i'm looking for python script is it possible to update both the parameter in recoverVMv2.py
 
 [Parameters](https://github.com/bseltz-cohesity/scripts/tree/master/python/recoverVMv2#parameters)
-v, --vip: Cohesity cluster to connect to
-u, --username: Cohesity logon username
-d, --domain: (optional) Cohesity logon domain (defaults to local)
-vm, --vmname: Name of VM to recover
-vc, --vcentername: (optional) name of vcenter to restore to
-dc, --datacentername: (optional) name of vsphere data center to restore to
-vh, --vhost: (optional) name of vSphere cluster or host to restore to
-s, --datastorename: (optional) name of datastore to restore to
-f, --foldername: (optional) name of vSphere folder to restore to
-n, --networkname: (optional) name of VM network to attach to
-x, --detachnetwork: (optional) leave network disconnected
-m, --preservemacaddress: (optional) keep same mac address
-t, --recoverytype: (optional) InstantRecovery or CopyRecovery (default is InstantRecovery)
-pre, --prefix: (optional) prefix to apply to VM name
-p, --poweron: (optional) power on the VM
-l, --listrecoverypoints: (optional) show available recovery points
-r, --recoverypoint: (optional) restore from a specific date, e.g. '2021-04-12 23:45:00' (default is latest backup)

**Comment by bseltz-cohesity** [comment]
Ah sorry I missed that you were talking about the python version. I have updated and renamed the new script,  here: https://github.com/bseltz-cohesity/scripts/tree/master/python/recoverVMsV2
