### ISSUE TITLE
How to install manually pyhesity ? 

### ISSUE THREAD

**Issue by charnoux** [bseltz-cohesity/scripts#126]
I am trying to test the python pyhesity module but I can't use curl to access external url from my enterprise servers. 
How can I get and install manually pyhestiy.py on my server in order that pyhesity module is recognized by python (ie. "from pyhesity import *" will work) ? 

Thanks to document the steps needed.

**Comment by bseltz-cohesity** [comment]
Hi @charnoux please see here: https://github.com/bseltz-cohesity/scripts/blob/master/python/DOWNLOADING.md
