### ISSUE TITLE
scripts/powershell /addObjectToUserAccessList

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#127]
I was having problem getting this to work with oracle linux server registrations.  

The output after the script runs shows it adds the server to the users group but it doesn't when I look at the access in Access Management for dp_cohesity_dbmgmt group .  

I was able to get the script to work with SQL servers just fine.

Example: In cohesity server: lx16155 is registered under Physical and Oracle source

./addObjectToUserAccessList_orig.ps1 -vip cluster `
                                     -username username `
                                     -domain domainname `
                                     -principalName okta/dp_cohesity_dbmgmt `
                                     -objectName lx16155
                                     

 
![lx16155](https://github.com/bseltz-cohesity/scripts/assets/104401071/80996128-af91-4b05-881b-926b631b9b07)
 

This is my output
 Connected!
okta\dp_cohesity_dbmgmt
    Adding lx16155

**Comment by bseltz-cohesity** [comment]
I just updated the script with a `-environment` parameter. In your case I think lx16155 is the name of both a physical protection source as well as a VM, and it's finding the VM. After getting the updated script, try adding `-environment kPhysical` or `-environment kOracle` to your command line.

**Comment by amhaats1** [comment]
Thank you, that worked great!!
