### ISSUE TITLE
scripts/powershell /protectO365Mailboxes

### ISSUE THREAD

**Issue by vincentmonin** [bseltz-cohesity/scripts#128]
Hello Brian, 

When I use this script in the context of a Cohesity organisation, I get the following error message:

![test](https://github.com/bseltz-cohesity/scripts/assets/149091352/c57d5322-9675-4fd3-9ea7-3be9d2bb16cc)

However, if I use the cohesity-api.ps1 SDK from August 2022, the connection goes through without a problem.

Thank's for you return. 

Best regards, 
Vincent MONIN

**Comment by bseltz-cohesity** [comment]
Hi @vincentmonin try getting the latest cohesity-api.ps1 file (just updated) here: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/cohesity-api

**Comment by vincentmonin** [comment]
Hi Brian, 
Thank you very much for your feedback ! 
Perfect, it's working now! I'm able to connect. And extracting mailboxes from the autoprotect job to a regular job works. 

Now I'm getting another error when I run the 2nd script (purging mailboxes from the autoprotect job to a classic job):
![image](https://github.com/bseltz-cohesity/scripts/assets/149091352/984748fc-8649-4523-a144-570d8791eb87)

Thank's for you return.

Best regards,
Vincent MONIN

**Comment by bseltz-cohesity** [comment]
I have updated the script, please get the update here and let me know if that solves it: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/protectO365Mailboxes

**Comment by vincentmonin** [comment]
Hi Brian, 

Thank's, it's working now ! 

Have a nice day. 

Best Regards, 
Vincent MONIN
