### ISSUE TITLE
scripts/oracle/python /protectOracle

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#129]
Can this be updated to protect more than one databases with comma separated (-db parameter) like the unprotectOracle script has to unprotect multiple -dn, --dbname: (optional) one or more database names to unprotect (repeat for multiple)?

**Comment by bseltz-cohesity** [comment]
Done. You can now say `-db ONEDB -db TWODB -db THREEDB`

**Comment by amhaats1** [comment]
Thanks again, working as described!! You are the best!!
