### ISSUE TITLE
Update vCenter script

### ISSUE THREAD

**Issue by natrlhy** [bseltz-cohesity/scripts#13]
1st thanks for these great scripts!

I noticed that the link to get the vCenter script is listed as this:
`https://raw.githubusercontent.com/bseltz-cohesity/scripts/master/oracle/python/updateVcenterCredentials/updateVcenterCredentials.py`

It should be:
`https://raw.githubusercontent.com/bseltz-cohesity/scripts/master/python/updateVcenterCredentials/updateVcenterCredentials.py `

Also is there a way with the 

`protectionSources/registrationInfo?includeEntityPermissionInfo=true&environments=kVMware`API to pull a list of know vCenter registered sources and updated the password based on known Sources on a cluster?

Thanks!

**Comment by bseltz-cohesity** [comment]
Thanks for the heads up. I just fixed the bad link. I'm already getting a list of vCenters with this line: `sources = api('get', 'protectionSources/registrationInfo?includeEntityPermissionInfo=true&environments=kVMware')`
It's the next line that filters that list down to only the one vCenter that matches the name we asked for: `sources = [source for source in sources['rootNodes'] if source['rootNode']['name'].lower() == sourcename.lower()]` so if you skip this line you can walk through each vCenter `for source in sources:`

**Comment by natrlhy** [comment]
Ah I see that now. I think what i was getting at was maybe having an option to have a switch or way to list the registered vCenter servers on the cluster with something like -l or --list. This would list the sources registered and use them in the -sn argument that's required

**Comment by bseltz-cohesity** [comment]
Can do, let me work on that
