### ISSUE TITLE
Add policy to an organisation with CLI or Script

### ISSUE THREAD

**Issue by vincentmonin** [bseltz-cohesity/scripts#132]
Hi Brian, 

I have open a ticket for this subject to a support Cohesity (Number 01464925) but they can't find. I'm writing to see if you have any ideas on how to add a policy (backup to S3) to an organisation ? 

Thanks for your help and sorry if this is off-topic.

I wish a nice day

Best Regards, 
Vincent MONIN

**Comment by bseltz-cohesity** [comment]
Hi Vincent, try this out... https://github.com/bseltz-cohesity/scripts/tree/master/powershell/orgAssignPolicy

**Comment by vincentmonin** [comment]
Brian, 

It works!  Thank you very much! 

Best regards, 
Vincent MONIN
