### ISSUE TITLE
Script for Bulk Restoring M365 Mailboxes and OneDrive Accounts

### ISSUE THREAD

**Issue by burnziii** [bseltz-cohesity/scripts#133]
I'm in search of a solution that can assist with automating the process of restoring multiple Microsoft 365 mailboxes and OneDrive accounts.

It would also be highly beneficial if the script included an option to download the restored OneDrive files as a ZIP archive. This would streamline the process of obtaining offline copies or creating backups of important files.

**Comment by burnziii** [comment]
Does it work for on prem cohesity cluster too?

**Comment by bseltz-cohesity** [comment]
No it's written for CCS. Sorry you did not specify

**Comment by bseltz-cohesity** [comment]
I don't have a bulk restore script for on-prem, you can ask your Cohesity sales team to submit a request for new script(s)
