### ISSUE TITLE
Restore SQL

### ISSUE THREAD

**Issue by dprior1985** [bseltz-cohesity/scripts#136]
Hello

I have been using RestoreSQL.ps1 for nearly 3 years now, with a few updates needed, just recently its stopped working. I have upgraded to the latest version of RestoreSQL.ps1 and now i'm getting a error stating Connected! (in green) but underneath Not Authenticated (in yellow).

I have tried modifying the code by removing everything after --passwd option as this want in the version i was using in the apiauth

in the code i have added an option to pull the account password from Environment variables 

your usage example doesn't show any new options that I need, your usage example is showing a log time restore where as I'm doing a latest request

Do you have any ideas on why this isnt working?

Many thanks

Danny

**Comment by bseltz-cohesity** [comment]
You likely have an outdated copy of cohesity-api.ps1. The download commands for restoreSQL.ps1 (and all of the powershell scripts in this repo) include commands to download the latest cohesity-api.ps1 as well. Please download both files again. Just confirmed the script is working fine.

**Comment by dprior1985** [comment]
Hello, This is better BUT now im getting an error saying that the Db on the server instance doesn't exist (it does) and i have confirm on the UI. Any ideas?

**Comment by bseltz-cohesity** [comment]
My guess is that you are not entering the -sourceServer correctly. I've seen many people enter the short name, but the server is registered as the FQDN. The server name must match exactly.

**Comment by dprior1985** [comment]
Hello, so i've alays used the IP address for the server, for so the source server is 192.168.0.0 and sourceDB ends up being 192.168.0.0/DB for example. this has always worked

**Comment by dprior1985** [comment]
Just looking at the UI, the SQL instances are held as 192.168.0.0/PROD for production instance. do i now need to include the instance name in the IP thus the source DB would be 192.168.0.0/PROD/DBA?

**Comment by bseltz-cohesity** [comment]
You should enter:
```powershell
-sourceServer 192.168.0.0 -sourceDB PROD/DBA
```

**Comment by dprior1985** [comment]
Hello, This is now working. thank you for taking the time to help me
