### ISSUE TITLE
powershell/agentGflags/agentGflags.ps1 - Unable to check agentGflags on linux servers

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#139]
cohesity/scripts/blob/master/powershell/agentGflags/agentGflags.ps1

This script only seems to work with windows servers since it uses WINRM

Can it be updated to accommodate for linux servers or create a python script for linux servers?

**Comment by bseltz-cohesity** [comment]
Yes that script is for Windows only. I'll consider a linux version but that will be very different, probably bash.

**Comment by bseltz-cohesity** [comment]
Check out any of the following:
[agentGflags](https://github.com/bseltz-cohesity/scripts/tree/master/linux/agentGflags) (linux) [New] set agent gflags via SSH
[agentGflags.exe](https://github.com/bseltz-cohesity/scripts/tree/master/windows/agentGflags) (windows) [New] set agent gflags via SSH
[agentGflags.py](https://github.com/bseltz-cohesity/scripts/tree/master/python/agentGflags) (python) [New] set agent gflags via SSH
