### ISSUE TITLE
Not an issue But Request | Question | VM auto-protect Jobs. 

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#14]
Hello Brain,

The below is not exactly an issue but requesting an idea. About how to get the data.
We are trying to avoid to use the Function "CohesityProtectionJobRun" as it would dump huge deal of data.

For Vms which are added manually to a Jobs. The protection job stores the server name as .SourceIds, No problem there. But those VMs which taking advantage of AutoProtect. The job does not stores the list of .SourceIds. it is protecting. 

We can get the ID (server names ) of the vms from by using. 
api get protectionSources/virtualMachines  ( no problem there )
 
But we cant relate the data from "protectionSources/virtualMachines" to any ID in the protection job.

We trying to find the list of VMS which are protected by a specific job (auto-protect). Without using protectionjobruns. 

Is it possible ?

**Comment by bseltz-cohesity** [comment]
Hi Rakesh,

Yes this is a bit tricky. You have to use recursion to walk the tree of protectionSources to find the object that is protected (in this case, a container like a VM folder), and then walk the tree below that folder to get all its descendent VMs, while confirming that each descendent is not in the exclusion list. In this example, I use two recursive functions in the example below. GetObjectById gets the folder object, and then GetAllChildren gets its descendent VMs.
```function getObjectById($objectId, $source){
    $global:_object = $null

    function get_nodes($obj){
        if($obj.protectionSource.id -eq $objectId){
            $global:_object = $obj
            break
        }
        if($obj.PSObject.Properties['nodes']){
            foreach($node in $obj.nodes){
                if($null -eq $global:_object){
                    get_nodes $node
                }
            }
        }
    }

    get_nodes $source
    return $global:_object
}

function getAllChildren($source, $excludeList){
    $global:_list = @()

    function get_nodes($obj){
        if($obj.protectionSource.id -notin $excludeList){
            if($obj.PSObject.Properties['nodes']){
                foreach($node in $obj.nodes){
                    get_nodes $node
                }
            }else{
                $global:_list += $obj
            }
        }
    }
    get_nodes $source
    return $global:_list
}

# get job that has autoprotected VM folder
$job = api get protectionJobs | Where-Object {$_.name -eq 'AutoTest'}

# get vCenter source for that job (note includeVMFolders)
$vCenterSource = api get "protectionSources?environments=kVMware&includeVMFolders=true" | Where-Object {$_.protectionSource.id -eq $job.parentSourceId }

# get list of excludedSourceIds if any
$excludeList = $job.excludeSourceIds
if($null -eq $excludeList){
    $excludeList = @()
}

# build list of protected VMs
$protectedVMs = @()


foreach($sourceId in $job.sourceIds){
    # find the folder object
    $protectedSource = getObjectById $sourceId $vCenterSource
    # get the child VMs of the folder
    $childVMs = getAllChildren $protectedSource $excludeList
    # add those child VMs to the list 
    $protectedVMs += $childVMs
}

# display the names of the VMs
foreach($vm in $protectedVMs){
    write-host $vm.protectionSource.name
}
```

**Comment by bseltz-cohesity** [comment]
I have posted the example here: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/listJobVMs

**Comment by RakeshMondalRon** [comment]
Awesome , thanks a ton. I got the data. More than what i expected. thanks a ton,
