### ISSUE TITLE
Registered sources - VSS check

### ISSUE THREAD

**Issue by pandaflourishingfish** [bseltz-cohesity/scripts#140]
When running the ["Registered Sources"](https://github.com/bseltz-cohesity/scripts/tree/master/reports/powershell/registeredSources) script,I have a server that returns as "Healthy".  However, if you look at the source in the GUI, it reports _"An error occurred while querying state of the VSS writer SqlServerWriter. Please try restarting the service SQL Server VSS Writer."_

Does the registered sources script check for this?

**Comment by bseltz-cohesity** [comment]
It should. I just ran a test by stopping the SQL VSS writer on a host and refreshed the source to produce an error, and the script detected it:
```
Cluster,Status,Source Name, Environment,Protected,Unprotected,Auth Status,Auth Error,Last Refresh,Refresh Error,App Health Checks
"VE4","Healthy","oracle19a.seltzer.net","Oracle","1","0","Finished","","1/16/2024 1:52:06 PM","","n/a"
"VE4","Healthy","oracle19b.seltzer.net","Oracle","1","0","Finished","","1/16/2024 1:52:12 PM","","n/a"
"VE4","Healthy","sql2016.seltzer.net","SQL","7","0","Finished","","1/16/2024 4:00:25 PM","","Passed"
"VE4","Unhealthy","sql2016b.seltzer.net","SQL","0","5","Finished","","1/16/2024 5:18:27 PM","","IsSQLWriterRunning: The service SQL Server VSS Writer is not running. Current state: SERVICE_STOPPED"
```

**Comment by pandaflourishingfish** [comment]
I should have taken a screenshot the other day, of course today all of my sources have VSS working as it’s supposed to.  When I have a good example, I can open a new issue.  Sorry for the hassle.



Carl Holzhauer, Managed Backup Sr
O 423-305-7890
 | D (423) 269-2543 | M 419-972-1295
***@***.***
1513 Cowart Street Chattanooga, TN 37408

​This electronic transmission and any attached documents or other writings are confidential and are for the sole use of the intended recipient(s) identified above. This message may contain information that is privileged, confidential or otherwise protected from disclosure under applicable law. If the receiver of this information is not the intended recipient, or the employee, or agent responsible for delivering the information to the intended recipient, you are hereby notified that any use, reading, dissemination, distribution, copying or storage of this information is strictly prohibited. If you have received this information in error, please notify the sender by return email and delete the electronic transmission, including all attachments from your system.

**Comment by bseltz-cohesity** [comment]
No worries, I believe you, I'm just not seeing the same issue in my testing. Let me know when you have a live example we can jump on zoom to debug...
