### ISSUE TITLE
Archives show up that have already been deleted.

### ISSUE THREAD

**Issue by mjamison7** [bseltz-cohesity/scripts#142]
When running the following commands there are dates that come up that when I go through the GUI it says that snapshot has already been deleted.

.\expireOldArchives.ps1 -vip $myserver -username $MyUsername -domain $MyDomain  -olderThan 60 -MFA ####

In the data that comes back I had a several snapshots that when I track down in the GUI it says the snapshots have been deleted

10/02/2022 18:00:00  PolicyName
08/01/2023 18:00:03  PolicyName

**Comment by bseltz-cohesity** [comment]
Hi @mjamison7 so are you saying it's a cosmetic error, are you saying that there are archives out there that the script should expire but it does not?

**Comment by mjamison7** [comment]
You had looked at it before (zoom call with dburg) and stated it was a cosmetic error.  The issue is on my cluster I seam to be getting more of these and I do not understand why they are still showing up even though the retention has pasted.

**Comment by bseltz-cohesity** [comment]
II think you will have to open a support case to let them look at the siren pages to determine why those are still showing. It's not a script problem, it only reports what it sees.

**Comment by bseltz-cohesity** [comment]
Go to the icebox (base) siren URL, then click on the "Icebox Master Location" link. Then scroll down to "Completed Archival Jobs"
