### ISSUE TITLE
JSON link is broken

### ISSUE THREAD

**Issue by pandaflourishingfish** [bseltz-cohesity/scripts#144]
Hi,

The link to the JSON file on the "[Cluster Backup Stats](https://github.com/bseltz-cohesity/scripts/tree/master/reports/grafana/PostgreSQL/ClusterBackupStats)" on the Grafana reporting page is broken.  The broken link is [this one](https://raw.githubusercontent.com/bseltz-cohesity/scripts/master/reports/grafana/PostgreSQL/ClusterBackupStats/ClusterBackupStats.json)  Clicking on it returns a 404 error

**Comment by bseltz-cohesity** [comment]
Fixed. Thanks!
