### ISSUE TITLE
oracle/python/restoreOracle-v2 issue will not restore the pluggable database

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#145]
Hi Brian we performed the below restores to overwrite original databases and it doesn't seem to be restoring the container/pluggable database(PDB),  It restores the CDB but not the PDB

We are currently testing on 6.8.1_u7 

We tried this option
./restoreOracle-v2.py -v mycluster \
                      -u myuser \
                      -d mydomain.net \
                      -ss oracleprod.mydomain.net \
                      -sd proddb \
                      -l -w

and this option and doesn't seem to be working

./restoreOracle-v2.py -v mycluster \
                      -u myuser \
                      -d mydomain.net \
                      -ss oracleprod.mydomain.net \
                      -sd CDB1/PDB1 \
                      -l -w

**Comment by bseltz-cohesity** [comment]
Try:

```
./restoreOracle-v2.py -v mycluster \
                      -u myuser \
                      -d mydomain.net \
                      -ss oracleprod.mydomain.net \
                      -sd CDB1 \
                      -pn PDB1 -pn PDB2 \
                      -l -o -w
```

**Comment by amhaats1** [comment]
Unfortunately it didn't work,  

I have attached some screen shots and comparing what the script looks performs and what it looks like if we perform the restore from the GUI.
[oracle_restore.docx](https://github.com/bseltz-cohesity/scripts/files/14425475/oracle_restore.docx)

**Comment by bseltz-cohesity** [comment]
I have updated the script: https://github.com/bseltz-cohesity/scripts/tree/master/oracle/python/restoreOracle-v2 please try:
```
./restoreOracle-v2.py -v mycluster \
                      -u myuser \
                      -d mydomain.net \
                      -ss oracleprod.mydomain.net \
                      -sd CDB1 \
                      -l -o -w
```
