### ISSUE TITLE
RestoreSQL

### ISSUE THREAD

**Issue by goforebroke** [bseltz-cohesity/scripts#146]
Restore SQL Command provides point in time restores for databases in the full recovery model using the "Point In Time Parameters". Does the restore command support restoring databases in the simple recovery model to a time other than the "latest"?

**Comment by bseltz-cohesity** [comment]
Hi @goforebroke, 

Yes, whether there are log backups or not, use the -logTime parameter to specify the point you want to restore to. If there are no log backups (as is the case for simple recovery DBs), the script will choose the most recent database backup that occurred at or before the specified -logTime.
