### ISSUE TITLE
addCustomHostMapping | Questions and Enhancement Request ?

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#15]
[ADDCustom Host Happing ](https://github.com/bseltz-cohesity/scripts/tree/master/powershell/addCustomHostMapping)
_(sorry for always coming with some issue)_
Hi The above works great. This one is more like enhancement Request.

Since we are dealing with Custom host mapping. I am always extra Cautious.

**1.Suggestion:** Would it be a good idea to add the below to the code ? To take a backups of the existing host mapping before updating anything ?

```
### authenticate
apiauth -vip $vip -username $username -domain $domain
#mycluterinfo
$clusinfo=api get basicClusterInfo

if (!$clusinfo)
{
            Write-Warning "Not Connected , I am out buddy "
            exit
}
echo $clusinfo.name
$datezz=get-date -format yyyy-MM-ddTHH-mm-ss

### get host mappings
$hosts = api get /nexus/cluster/get_hosts_file

##lets backup before we append
$hosts2=$hosts.hosts
echo $hosts2 > backupmyhosts$datezz.txt
```
**2. Question:** I have a habit of running the code line by line , before testing it out in Real world. I have a question with respect to below. 

`$hosts.hosts = @($hosts.hosts + @{ 'ip' = $ip; 'domainName' = @($hostNames)})`

After appending the new host entry to $hosts.hosts with above  , i can never see the in the output screen if I do
"echo $hosts.hosts ", it shows the existing entry and some blank spaces at the bottom. I know it does update the new value. But on my screen it never shows new value,  untill I update "api put"and  get a new list with " api get /nexus/cluster/get_hosts_file".

**3.The script** updates only one value, it is possible to have a list of IP and hosts added ?
Ideas ?

**Comment by bseltz-cohesity** [comment]
Hi Rakesh,

I will update the script with these features shortly...

**Comment by bseltz-cohesity** [comment]
Script has been updated! https://github.com/bseltz-cohesity/scripts/tree/master/powershell/addCustomHostMapping
