### ISSUE TITLE
Add taskname in VM restore jobs

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#152]
Hi Brian,

thanks for updating taskname in restorefile script. Could you please update same for below scripts it will be helpful.

https://github.com/bseltz-cohesity/scripts/blob/master/powershell/restoreVMFiles/restoreVMFiles.ps1

https://github.com/bseltz-cohesity/scripts/blob/master/powershell/recoverVM/restoreVM.ps1

**Comment by Sheeba86** [comment]
I could see task name is updated with task string in https://github.com/bseltz-cohesity/scripts/blob/master/powershell/restoreVMFiles/restoreVMFiles.ps1, please ignore for this script.

**Comment by bseltz-cohesity** [comment]
The VM restore script has a -taskName parameter: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/recoverVMs

I have removed the older recoverVM script.
