### ISSUE TITLE
registerVcenter.ps1 useVmBiosUuid

### ISSUE THREAD

**Issue by jidelaf** [bseltz-cohesity/scripts#153]
Hi Brian,
In powershell script script [registerVcenter.ps1](https://github.com/bseltz-cohesity/scripts/tree/master/powershell/registerVcenter) 
Would it be possible to have the option to enable the GUI option "_Use VM BIOS UUID to track virtual machines_" ?

I believe it could be this parameter **useVmBiosUuid**

https://developer.cohesity.com/apidocs/681-v2/#/http/api-endpoints/source/register-protection-source

That's an option that can only be set when registering a vcenter and can't be modified afterward.
And we do require it in all our vcenters.
It would be great to have that option so we can fully automate our new Vcenter configurations

Thank you!

**Comment by bseltz-cohesity** [comment]
Done! https://github.com/cohesity/community-automation-samples/tree/main/powershell/registerVcenter

**Comment by jidelaf** [comment]
Amazing!
Thank you!
