### ISSUE TITLE
powershell/recoverVMs/recoverVMs.ps1

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#155]
i'm trying to vm using protectiongroup and using following parameters  vcentername, datacenter, datastorename and networkname but script is exiting with hostname required. could you please check it and can we make this as optional?

**Comment by bseltz-cohesity** [comment]
I can not make it optional, It's mandatory in the API. Specify the name of the HA cluster if your ESXi hosts are clustered.
