### ISSUE TITLE
Can't get anti-archive operators to work

### ISSUE THREAD

**Issue by dragongeek** [bseltz-cohesity/scripts#157]
Each time I run backupNow.py, it runs the Archives to the Cloud even though one is set to monthly, and the other is set to weekly. I tried the flags "-l" "-nr" and "-na", separate and together, and it always runs the cloud archives. I checked your documentation and don't see any hints that I'm using them incorrectly. Below is the command line as executed:
./backupNow.py -v liscohobkup -u apiuser -d local -j RHEL-UV-PRD -y -w -nr -na -l

**Comment by bseltz-cohesity** [comment]
Fixed. Note that -y is deprecated (does nothing). -l will cause both replication and archival to be skipped. -na causes archival to be skipped,  and -nr causes replication to be skipped. Using -l and -na or -nr is redundant but will work fine.

**Comment by dragongeek** [comment]
I edited the command line, but it still queued both of the Cloud Archives. This is my command line now:
[root@radar bin]# ./backupNow.py -v liscohobkup -u apiuser -d local -j RHEL-UV-PRD -l -w
Connected!
Running RHEL-UV-PRD...

**Comment by bseltz-cohesity** [comment]
Sorry I should have been more clear. Fixed version is here, please get the updated version: https://github.com/cohesity/community-automation-samples/tree/main/python/backupNow

**Comment by dragongeek** [comment]
Oh, Great! Thanks! Every time I talk to my boss about these scripts, I tell him what a Rock Star you are about making updates when contacted. Works great now!

**Comment by dragongeek** [comment]
Oh, one more question. Do I have to program around turning the archive on and off? When run from the UI on schedule, it seems to know to only run the archives per the policy. We have one which is supposed to run weekly and is kept short-term, and another which is supposed to run monthly and is kept long term, but they run every time when run from the backupNow.py script.

**Comment by bseltz-cohesity** [comment]
Right, like the run now dialog in the UI, backupNow does not respect the day of week/month/year. To do so would add a lot of complexity. For now the best approach is to run the script on you weekly/monthly schedule with the appropriate options for each schedule.

**Comment by dragongeek** [comment]
Thanks Brian!

Michael Randall
