### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by komoreka** [bseltz-cohesity/scripts#16]
Hi Brian,

I am trying to:
a) change virtual network when restoring
b) if possible change also ip although not sure if that feature is out with cohesity if not will possibly use vmware api

tried to edit/add to your code on part below but not sure if that should to work and how to get actual target id:

"name"                         = "Recover-$($protectedVM.registeredSource.id)-$recoverDateString";
                    "objects"                      = @();
                    "vmwareParameters"             = @{
                        "networkMappings" = @{
                            "targetNetworkId" = "ID_HERE"
                        }
                
                    };

                    "powerStateConfig"             = @{
                        "powerOn" = $false
                    };
                    "restoredObjectsNetworkConfig" = @{
                        "disableNetwork" = $false
                    };
                    "continueRestoreOnError"       = $false;
                    "vaultRestoreParams"           = @{
                        "glacier" = @{
                            "retrievalType" = "kStandard"
                        }
                    }
                }

Could you please assist?

**Comment by bseltz-cohesity** [comment]
First you have to identify the network ID:
```### find vSphere recovery target pool, datastore, folder, network
$resourcePools = api get "/resourcePools?vCenterId=$vCenterId" | where-object { $_.resourcePool.displayName -eq $vmResourcePool }
$resourcePoolId = $resourcePools[0].resourcePool.id

$networks = api get "/networkEntities?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId" | Where-Object { $_.displayName -eq $vmNetwork }
```
then you can assign the network id:
```    'restoredObjectsNetworkConfig' = @{
        'networkEntity' = $networks[0];
        'disableNetwork' = $false
    };```
See this script for example: https://raw.githubusercontent.com/bseltz-cohesity/scripts/master/powershell/recoverVMJob/recoverVMJob.ps1

**Comment by komoreka** [comment]
I tried to look at that script and looks like on version 6.4.1a 

$datastores = api get "/datastores?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId" | Where-Object { $_.vmWareEntity.name -eq $vmDatastore }
$vmFolders = (api get "/vmwareFolders?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId").vmFolders  | Where-Object { $_.displayName -eq $vmFolder }
$networks = api get "/networkEntities?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId" | Where-Object { $_.displayName -eq $vmNetwork }

I can get results for $vmfolders only even if i skip "Where" from pipeline.

I cannot get results for $datastores and $networks I still use same $resourcePoolId and $vCenterId

**Comment by komoreka** [comment]
ok I found some issue with permissions on account I was using for that task.
API did not informed there is not privilege just showed no results will keep you posted

**Comment by komoreka** [comment]
ok script you proposed is recovering job I rather use below:

https://raw.githubusercontent.com/bseltz-cohesity/scripts/master/powershell/restoreVMs/restoreVMs.ps1

would like to edit this one so it works with changing network

**Comment by bseltz-cohesity** [comment]
Here's how to do it for a single VM. I will make some more improvements and publish this script in the coming days...
```
### process commandline arguments
[CmdletBinding()]
param (
    [Parameter(Mandatory = $True)][string]$vip,
    [Parameter(Mandatory = $True)][string]$username,
    [Parameter()][string]$domain = 'local',
    [Parameter(Mandatory = $True)][string]$vmName,
    [Parameter(Mandatory = $True)][string]$vCenter,
    [Parameter()][string]$vmResourcePool = 'Resources',
    [Parameter(Mandatory = $True)][string]$vmDatastore,
    [Parameter()][string]$vmFolder = 'vm',
    [Parameter(Mandatory = $True)][string]$vmNetwork
)

### source the cohesity-api helper code
. $(Join-Path -Path $PSScriptRoot -ChildPath cohesity-api.ps1)

### authenticate
apiauth -vip $vip -username $username -domain $domain

### find the VMs to recover
$vms = api get "/searchvms?entityTypes=kVMware&vmName=$vmName"
$exactVMs = $vms.vms | Where-Object {$_.vmDocument.objectName -eq $vmName}
$latestsnapshot = ($exactVMs | sort-object -property @{Expression={$_.vmDocument.versions[0].snapshotTimestampUsecs}; Ascending = $False})[0]

### find vCenter
$hv = api get '/entitiesOfType?environmentTypes=kVMware&vmwareEntityTypes=kVCenter' | Where-Object { $_.displayName -eq $vCenter }
$vCenterId = $hv[0].id

### find vSphere recovery target pool, datastore, folder, network
$resourcePools = api get "/resourcePools?vCenterId=$vCenterId" | where-object { $_.resourcePool.displayName -eq $vmResourcePool }
$resourcePoolId = $resourcePools[0].resourcePool.id

$datastores = api get "/datastores?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId" | Where-Object { $_.vmWareEntity.name -eq $vmDatastore }
$vmFolders = (api get "/vmwareFolders?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId").vmFolders  | Where-Object { $_.displayName -eq $vmFolder }
$networks = api get "/networkEntities?resourcePoolId=$resourcePoolId&vCenterId=$vCenterId" | Where-Object { $_.displayName -eq $vmNetwork }

### build recovery task
$recoverDate = (get-date).ToString().Replace(' ','_').Replace('/','-').Replace(':','-')

$myObject = @{
    'name' = "Recover-$vmName-$recoverDate";
    'objects' = @(
        @{
            'entity' = $latestsnapshot[0].vmDocument.objectId.entity
            'jobId' = $latestsnapshot[0].vmDocument.objectId.jobId;
            'jobUid' = $latestsnapshot[0].vmDocument.objectId.jobUid;
            'jobInstanceId' = $latestsnapshot[0].vmDocument.versions[0].instanceId.jobInstanceId
            'startTimeUsecs' = $latestsnapshot[0].vmDocument.versions[0].instanceId.jobStartTimeUsecs
            '_jobType' = 1
        }
    );
    'powerStateConfig' = @{
        'powerOn' = $true
    };
    'restoredObjectsNetworkConfig' = @{
        'networkEntity' = $networks[0];
        'disableNetwork' = $false
    };
    'continueRestoreOnError' = $false;
    'restoreParentSource' = $hv[0];
    'resourcePoolEntity' = $resourcePools[0].resourcePool;
    'datastoreEntity' = $datastores[0];
    'vmwareParams' = @{
        'targetVmFolder' = $vmFolders[0]
    }
}

"Restoring VMs..."
$null = api post /restore $myObject
```

**Comment by komoreka** [comment]
awesome thank you !

**Comment by komoreka** [comment]
works good only thing what was missing is param for vmfolder and what I would add it optional name prefix in my case there is no issue since I am restoring to isolated network but ppl might need that. do you know if via restapi is possible to re-ip ?

**Comment by bseltz-cohesity** [comment]
re-ip is being planned to be added to the product. I will include the vmFolder and prefix in the script...

**Comment by bseltz-cohesity** [comment]
I have published a new version: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/recoverVM

**Comment by komoreka** [comment]
Awesome thank you !
