### ISSUE TITLE
Error restoring from replicated cohesity cluster

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#161]
Hi Brian,
 Below script i'm using to restore data from replicated cohesity cluster, its giving error as source is not registered. could you please check from your end.

powershell/restoreFiles/restoreFiles.ps1

**Comment by bseltz-cohesity** [comment]
Works fine for me. In my example, backup of server1 (protected at cluster1) has been replicated to cluster2, and I'm restoring a file to server2 (registered at cluster2).
```
PS ~/scripts/powershell> ./restoreFiles.ps1 -vip cluster2 -username myuser -sourceServer server1.mydomain.net -targetServer server2.mydomain.net -fileNames /home/myuser/test.txt -restorePath /home/myuser 
Connected!
Restoring /home/myuser/test.txt from 06/06/2024 14:58:04 (local)
```

**Comment by bseltz-cohesity** [comment]
Please try adding the `-noIndex` option to your command line

**Comment by Sheeba86** [comment]
it worked now thanks for your support

**Comment by Sheeba86** [comment]
Hi Brian,

 I found one glitch when i redirect the  restore to different server after restore starts, in GUI when i check options it shows restoring to the original destination, actually its restoring to destination server and path which i specified but its not showing same in actual target servername and restore path in the GUI option, could you please verify it. 
 
Details
Options
Recover To Original Server
Recover to Original Path Yes
Overwrite Existing File/Folder No
Preserve File/Folder Attributes Yes
Continue on Error Yes
Save Success Files No
Cluster Interface Auto Select

**Comment by bseltz-cohesity** [comment]
Yes I see that. It's a UI bug so you should open a support case to report it. It has nothing to do with the script.

**Comment by Sheeba86** [comment]
ok thanks for your support.
