### ISSUE TITLE
https://github.com/bseltz-cohesity/scripts/tree/master/powershell/updateJob

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#162]
Would it be possible to add a parameter to update the Alerts sections to be able to turn on or off any of these

Alerts
Alert On: Failure
Alert On: SLA Violation
Alert On: Success

**Comment by bseltz-cohesity** [comment]
OK I have added the following parameters:
-alertOn: (otional) one or more of the following: None, kSuccess, kSlaViolation, kFailure' (comma separated)
-addRecipient: (optional) one or more email addresses to add to alert recipients (comma separated)
-removeRecipient: (optional) one or more email addresses to remove from alert recipients (comma separated)

**Comment by amhaats1** [comment]
Thank you, that worked.
