### ISSUE TITLE
https://github.com/bseltz-cohesity/scripts/tree/master/python/protectUDA  add alerton functionality

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#163]
https://github.com/bseltz-cohesity/scripts/tree/master/python/protectUDA

Could you by chance add the AlertOn function to this python script like you did for me with powershell/updatejob.ps1 script?

**Comment by bseltz-cohesity** [comment]
Done:
* -al, --alerton: (optional) None, kFailure, kSuccess or kSlaViolation (repeat for multiple)
* -ar, --recipient: (optional) email address to send alerts to (repeat for multiple)

**Comment by amhaats1** [comment]
Confirmed this worked! Thank you!!, sorry for the late reply
