### ISSUE TITLE
Multiple extension files to find

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#164]
Hi Brian,

i'm using below script to find the files with particular extension. But i can't able to use multiple extension.  
Is it possible to update the script to use multiple extension simultaneously?

powershell/findFiles/findFiles.ps1

**Comment by Sheeba86** [comment]
Hi Brian,

I tried to run the script but its not working as expected. New script i used as findfilesv1.ps1 its not giving me the output. Could you please check it. Old script works with one search string, updated script is not working with single or multiple string.

PS D:\CohesityPS> .\findFilesv1.ps1 -vip cohesityclu.local -username abcd123 -objectName server1.local -jobName Protect_Job1 -searchString bak, trn -extensionOnly
Connected!

0 indexed files found

saving results to foundFiles.tsv

PS D:\CohesityPS> 
PS D:\CohesityPS> .\findFilesv1.ps1 -vip cohesityclu.local -username abcd123 -objectName server1.local -jobName Protect_Job1 -searchString bak -extensionOnly
Connected!

0 indexed files found

saving results to foundFiles.tsv

PS D:\CohesityPS> .\findFiles.ps1 -vip cohesityclu.local -username abcd123 -objectName server1.local -jobName Protect_Job1 -searchString bak -extensionOnly
Connected!
,server1.local,/D/backup/Test_full_backup.bak,

**Comment by bseltz-cohesity** [comment]
Sorry there was a bug when using -extensionOnly. I've updated it, please download again.

**Comment by Sheeba86** [comment]
Now script is working as expected. Thanks for support.
