### ISSUE TITLE
FolderName required for VM Restore

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#167]
Script : powershell/recoverVMs

i tried to give the path as per your parameter notes but i'm getting error **folder not found** or is it possible update restore the default path of the datastore we specify in the parameter  or How to identify the Folder path in the ESXi end.

**Comment by bseltz-cohesity** [comment]
The `-folder` parameter specifies the vSphere folder to place the VM, not the directory path in the datastore. Example:
```
./recoverVMs.ps1 -vip mycluster -username myuser -vmName linux8a -vCenterName vcenter67.seltzer.net -hostName myhost1 -datacenterName home -detachNetwork -datastoreName nvme-201 -prefix test -folderName /test/restores
```
<img width="228" alt="Screenshot 2024-07-03 at 7 14 14 AM" src="https://github.com/bseltz-cohesity/scripts/assets/38843677/76f17f4b-72a4-43d1-8530-b2d085ae2279">

**Comment by Sheeba86** [comment]
I'm trying to restore the VM to different Vcenter, as per above comments i'm restoring to vSphere folder name but its showing folder not found error.  Is script verifying the source VM folder path?

**Comment by Sheeba86** [comment]
ignore above comments, i identified the issue.
