### ISSUE TITLE
Filelist creating multiple restore jobs

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#168]
Hi Brian,

 When i'm trying to restore multiple files added into text file and restoring, script is creating individual restore jobs instead of updating in single job is this behaviour is expected. Could you please check it.

Script Name: powershell/restoreFiles/restoreFiles.ps1

Command Used
.\restorefiles.ps1 -sourceServer server1.local.net -targetServer server2.local.net -jobName backupjob1 -restorePath  /app/testrestore/ -taskname testing_filerestore_script -fileList D:\RestoreTesting\filelist.txt

Restore Job Output
Recovery Task  					Start Time 			Status 		Duration
testing_filerestore_script		Jul 3, 2024 6:39am 	Succeeded 		6s
1 Objects

testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects

testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects

testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects
	
testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects
	
testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects
	
testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects

testing_filerestore_script 		Jul 3, 2024 6:38am	Succeeded 		6s
1 Objects

**Comment by bseltz-cohesity** [comment]
Yes this is expected behavior, as each selection may be located in different snapshots. To make it restore all in one task, use the `-latest` parameter or the `-runId` parameter.
