### ISSUE TITLE
BackupNow.ps1 KEEPLOCAL option

### ISSUE THREAD

**Issue by pge92** [bseltz-cohesity/scripts#169]
Hi Brian, 
thx for your numerous scripts that are very useful for extended functionalities
i'm very sad that the _keeplocal_ option is no more working in BackupNow.ps1 as it is now deprecated. i was using it to do 'special on-demand backups with mid-term extended retention for specific objects'  
i had a look into your other scripts but did not find any other script able to do this task (or i did not search correctly). do you plan to re-add this functionality ? or perhaps it is possible to do this using another script ?
best regards
Pierre

**Comment by bseltz-cohesity** [comment]
I've re-added the keepLocalFor functionality. It was unsupported for a time but works again now.

**Comment by pge92** [comment]
great, thx :)
