### ISSUE TITLE
Bugs in Custom addCustomHostMapping 

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#17]
We tested the current version in our Test cluster and we found the below.

[https://github.com/bseltz-cohesity/scripts/tree/master/powershell/addCustomHostMapping](url)

1 . If the host mapping of a cluster is empty ( A cluster never been updated with even single entry ) and is attempted to update one host with IP and Name like below,

.\addCustomHostMapping.ps1 -vip testCluster -username my -ip 192.168.1.1 -hostNames server1 -backup

the it throws error and does not update.

Connected!
**Error while parsing request body: json: cannot unmarshal object into Go struct field ClusterUploadHostsFileReq.hosts of type []utils.EtcHostEntry**

However the if we update with -inputFile, the it works fine. This is not a big issue. 

2. The Input file.
Desc: "-inputFile: (optional) csv file containing ip,hostname1,hostname2,hostname(n)"
If we input CSV file with below format, in single cell

192.168.1.11,MYServer1
192.168.1.12,MYServer2

then it does not want to update.

Error **"Invalid IP "192.168.1.11"**

It updates only if we provide cell by cell without comma in the inputfile.csv ( Cell A with IP , Cell B with Name )

192.168.168.11 MYServer1
192.168.168.12 MYServer2

3. The input file does not accept more than one host name for an IP in the same file. 
**Error: "Invalid domian name"**

192.168.168.11 MYServer1
192.168.168.12 MYServer2 MYServer2.FQDN.com

It work if we state in next line with same IP. Something like this. 
192.168.168.12 MYServer2
192.168.168.12 MYServer2.FQDN.com

Thanks 
Ron

**Comment by bseltz-cohesity** [comment]
fixed! Thanks for finding this...

**Comment by RakeshMondalRon** [comment]
that was super Quick. Testing same, thanks a ton :)
