### ISSUE TITLE
cancelRunningJobs vs cancelRunningObject, trying to cancel single protection job

### ISSUE THREAD

**Issue by dragongeek** [bseltz-cohesity/scripts#170]
I'm trying to cancel a single running protection job, but can't tell from the parameters list if or how this is possible using your python scripts. I don't understand the reference to "an object"  in cancelRunningObject,  and don't see a protection job name or ID in cancelRunningJobs. Apologies if I'm missing this. A couple of examples might help if the functionality is there and I'm just not understanding.

**Comment by bseltz-cohesity** [comment]
```
./cancelRunningJobs.py -v mycluster -u myuser -j 'my job name'
```

**Comment by dragongeek** [comment]
Super-de-duper. Thanks Brian. That works.
