### ISSUE TITLE
Question: Restore a Database from a tenant owned VM to a shared dev system

### ISSUE THREAD

**Issue by HenrikFFM** [bseltz-cohesity/scripts#172]
Hello Brian,

we have our production systems for our customers separated in tennants. 
One of our customer has a need to separate the vms for one some his customers from the other vms.
So we built this in cohesity. All is fine.

But our customer want to use a central dev sql server for different projects.
So i have to restore a Database from one tennant to a sql sever that is located in an other tennant.

How can i do this ?

**Comment by bseltz-cohesity** [comment]
To my knowledge , cross-tenant restore is not possible. You can only restore to a destination that is registered in the same tenant.

**Comment by HenrikFFM** [comment]
Thank you for the fast answer.
