### ISSUE TITLE
Restore VM using protectiongroup

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#173]
Hi Brian,

 I have scenario, where one of the VM backing up in two protection group. I need to restore the VM from one particular protection group, when I use protectiongroup option its restoring the all the vm in that protectiongroup. Is it possible to update the script when i provide vmname and protectiongroup it should restore only that VM?

Script Name: powershell/recoverVMs

**Comment by bseltz-cohesity** [comment]
Done, I've added a -jobName parameter: https://github.com/cohesity/community-automation-samples/tree/main/powershell/recoverVMs

**Comment by Sheeba86** [comment]
Looks good Thanks for your Support 👍
