### ISSUE TITLE
Restore Report not giving correct duration for VM's restore

### ISSUE THREAD

**Issue by Sheeba86** [bseltz-cohesity/scripts#174]
Hi Brian,

  I have query with reporting of restore, I have multiple VM's restored in a restore job, but shows same duration for all the VM's instead of actual duration. could you please check it.

reports/powershell/restoreReport/restoreReport.ps1

**Comment by bseltz-cohesity** [comment]
The script is working as designed. It reports the start time and duration of the recovery task, not the individual objects. To get the object-level would require the script to run an API call for every object reported, which would be slow and impactful to the cluster.

**Comment by Sheeba86** [comment]
Ok thanks your support
