### ISSUE TITLE
Add indexing parameters to update job scripts

### ISSUE THREAD

**Issue by amhaats1** [bseltz-cohesity/scripts#175]
powershell/updateJob.ps1
python/updateJobSettings.py

Can you add in a couple more parameters to enable/disable indexing with include/exclude paths as well?

**Comment by bseltz-cohesity** [comment]
This one is a bit complicated so I will deliver this in stages. I've updated the PowerShell script with two new parameters:

-enableIndexing: (optional) enable indexing (applies the default include and exclude paths)
-disableIndexing: (optional) disable indexing

The updated script is here: https://github.com/cohesity/community-automation-samples/tree/main/powershell/updateJob

I'll comment further as I progress.
