### ISSUE TITLE
Increase timeouts for API call. 

### ISSUE THREAD

**Issue by ashish-cohesity** [bseltz-cohesity/scripts#18]
Hi Brian, 

Sometimes, based on the size of the env and endpoints, the return for a particular api could be ~90 seconds. Default Powershell HTTP is 100 seconds. It'd be great if you want to factor this in. Couple of SREs reported me this.  

https://github.com/bseltz-cohesity/scripts/blob/cc29bb13dfabfac977579142bc3bc2ddceb20013/powershell/cohesity-api/cohesity-api.ps1#L361

**Comment by bseltz-cohesity** [comment]
You recommend I set the timeout to 100 secs?

**Comment by ashish-cohesity** [comment]
Powershell sets it to 100 by default : https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?redirectedfrom=MSDN&view=netcore-3.1#System_Net_HttpWebRequest_Timeout  , In Cohesity Powershell, we are just sending the request without the parameter.

**Comment by bseltz-cohesity** [comment]
Got you. I will remove that parameter...

**Comment by bseltz-cohesity** [comment]
Fixed!
