### ISSUE TITLE
protectionRunsReport / invalid column content SOURCENAME for some replication flows

### ISSUE THREAD

**Issue by pge92** [bseltz-cohesity/scripts#180]
hi, 
again thx for these pwsh and py usefull scripts
it seems there is an "error" in the output of the clusterProtectionRuns.ps1, concerning the replicated data. when the extract is replication, the SourceName column is not correctly filled : it is filled with the content of ObjectName (see example)
i've found it for the plugins kExchange and kNetapp. Seems to be correct for kVmware, kSQL, kAD, kPhysical

here the HEADERS : 

protectionRunsReport-2024-09-24.csv			:Start Time,End Time,Duration,status,slaStatus,snapshotStatus,**_objectName,sourceName_**,groupName,policyName,Object Type,backupType,System Name,Logical Size GiB,Data Read GiB,Data Written GiB,Organization Name,DataLock Expiry
repli_protectionRunsReport-2024-09-24.csv	:Start Time,End Time,Duration,status,slaStatus,snapshotStatus,**_objectName,sourceName_**,groupName,policyName,Object Type,backupType,System Name,Logical Size GiB,Data Read GiB,Data Written GiB,Organization Name,DataLock Expiry

and an example of line (first one the backup job, second one the replication job):

protectionRunsReport-2024-09-24.csv			:2024-09-10 06:00:02,2024-09-10 07:34:58,5696,kSuccess,Met,Active,**_FS_Apps_XXX2,svmdlab40_**,NAS_svmdlab_NFS,Daily_2months_Q1Y_RepliDE,kNetapp,kRegular,clusterxxxxx,8323.2,14.3        ,2.0,,2024-09-25 06:00
repli_protectionRunsReport-2024-09-24.csv	:2024-09-10 06:00:02,2024-09-10 07:34:58,5696,kSuccess,Met,Active,**_FS_Apps_XXX2,FS_Apps_XXX2_**,NAS_svmdlab_NFS,-,kNetapp,kRegular,clusteryyyyy,8323.2,14.3,0.0,,

say me if it is not clear enough with the explanations
is there a way to get the correct SourceName ?
best regards

**Comment by bseltz-cohesity** [comment]
Thanks for your feedback. The behavior you see is intentional. For some environments, the registered source name can not be determined for replicated runs. So the script fills in the blank with the object name.

**Comment by pge92** [comment]
ok, i guessed so as the replicated files POLICY was filled with a minus.
thx for the explanation
