### ISSUE TITLE
oracleLogDeletionDaysReport

### ISSUE THREAD

**Issue by isheehan-q** [bseltz-cohesity/scripts#181]
Hi Brian,

when running the oracleLogDeletionDaysReport.py script an error is encountered, 
Connected!
Traceback (most recent call last):
  File "./oracleLogDeletionDaysReport.py", line 76, in <module>
    for instance in thisSource['applicationNodes']:
KeyError: 'applicationNodes'

Any suggestions on how to fix/avoid the error?,

thanks

**Comment by bseltz-cohesity** [comment]
Hi you appear to be using an old version of the script. Please find the updated version here: https://github.com/cohesity/community-automation-samples/tree/main/oracle/python/oracleLogDeletionDaysReport

**Comment by isheehan-q** [comment]
Great, 
thanks Brian , working now, really useful script,
Ivan
