### ISSUE TITLE
Can't find a way to generate a jobs success/failure status report for a time period (Python/pyhesity)

### ISSUE THREAD

**Issue by dragongeek** [bseltz-cohesity/scripts#182]
I have tried several of your python scripts but cannot generate the report my management is requesting. They want the status (failed/success) for a couple of specific protection jobs, for a specific time period. In this current case, the past 6 months plus (2024-06-01 - 2024-11-10). I can generate the list of all protection jobs, or the last run of specified jobs, but cannot figure out how to generate what is requested above. Apologies if I've missed it. 
FWIW, I've tried ./backedUpFileList.py, ./jobMonitor.py, ./jobList.py, ./jobDumper.py and ./protectionRunsV1Example.py.

**Comment by bseltz-cohesity** [comment]
Rather than trying to script it, why don't you look at the Helios report "Protection Activities"? https://helios.cohesity.com/reporting/detail/protection-activity

Use the filters and you can get exactly the report you are looking for.
