### ISSUE TITLE
stats for 'time taken for replication'

### ISSUE THREAD

**Issue by pge92** [bseltz-cohesity/scripts#184]
Hello, 
once again congrats for all these useful scripts :)
i'd like to get an information very useful on the GUI : the 'time taken for the replication'. in all the scripts dealing with replication i did not find this information - perhaps i did not search well.
is there a way to get it ? i have to build a report dealing with replication SLA between our sites, and to raise alerts when replication time is significantly increasing
thank you for your help
see the screenshot displaying the information :
![2024-11-19_11h33_07](https://github.com/user-attachments/assets/1b28a45d-88b5-43ac-a024-cae4bb9827b1)

thank you for your help
regards

**Comment by bseltz-cohesity** [comment]
Try this script https://github.com/cohesity/community-automation-samples/tree/main/reports/powershell/replicationReport

**Comment by pge92** [comment]
great, exactly what i was looking for ; the information needed is in one of the CSVs. thx 👍
