### ISSUE TITLE
backupNow.py - doesnt work with tennants

### ISSUE THREAD

**Issue by HenrikFFM** [bseltz-cohesity/scripts#185]
We want to use an nfs share in Cohesity and the replication mechanism in a protection job to transfer the data between two locations.
Both locations have a local cohesity.
The nfs share is part of a tennant and the protection job too.

When the app backup to the nfs share is done, we want to trigger the nfs protection job inside cohesity.

But these backupnow say that he doesnt found the job.

**Comment by bseltz-cohesity** [comment]
Fixed. I've added a -tenant (--tenant) parameter: https://github.com/cohesity/community-automation-samples/tree/main/python/backupNow

**Comment by HenrikFFM** [comment]
Thank you Brian!

And i have another thing:
the Doku say: 

-pwd, --password: (optional) password or API key

but the Script await -p for password.

Not shure which one is the planned one.

**Comment by bseltz-cohesity** [comment]
It's -p doc fixed

**Comment by HenrikFFM** [comment]
Thank you for the fast help
