### ISSUE TITLE
How to display all supported cluster Gflags

### ISSUE THREAD

**Issue by EdenCore** [bseltz-cohesity/scripts#187]
Hello Brian,

First of all, huge respect for the tremendous work you are doing here.

I would like to ask one question : using the scripts in the repository (for example `/powershell/gflags/gflags.ps1`), we can view the Gflags that *have been set* on the cluster.

Is there a method to view all the possible Gflags names ?

Best regards

**Comment by EdenCore** [comment]
Looks like I found the command : 

`iris_cli cluster ls-gflags verbose=true` thanks to [this link](https://forum.cristie.com/t/cobmr-gflag-check/818)

**Comment by bseltz-cohesity** [comment]
Yes.
PowerShell: https://github.com/cohesity/community-automation-samples/tree/main/powershell/gflagList
Python: https://github.com/cohesity/community-automation-samples/tree/main/python/gflagList
