### ISSUE TITLE
Physical / SQL Decomission

### ISSUE THREAD

**Issue by komoreka** [bseltz-cohesity/scripts#20]
Hi Brian I am working on my side on decommission process and realize you do not have it unless I am blind.

except default auth params we should use:  vmname
action should be:
1. check if object is in protection source 
2. if yes decom it 
3. If part of job will give you notification therefore: 
 a) remove from job
 b) decom it again

unless you have better method plan
I saw you have it for VM but not for physical

**Comment by komoreka** [comment]
oh sorry found it my bad !

**Comment by bseltz-cohesity** [comment]
Unregistering a physical protectionSource is pretty straightforward...
```apiauth ve3 admin
$sources = api get protectionSources?environments=kPhysical                       
$myserver = 'centos2.seltzer.net'                                                 
$mysource = $sources.nodes | Where-Object {$_.protectionSource.name -eq $myserver}
api delete protectionSources/$($mysource.protectionSource.id)```

**Comment by komoreka** [comment]
not when part of job
I did create my script now but it is not clean as your way basically it goes like I said:
check if object is in protection source
if yes decom it
If is part of the job:
a) remove from job or if only one object delete job 
b) decom it again

**Comment by bseltz-cohesity** [comment]
Right, you first need to remove it from any jobs. I show you how to do this here: https://github.com/bseltz-cohesity/scripts/blob/master/powershell/unprotectPhysicalServer/unprotectPhysicalServer.ps1

**Comment by komoreka** [comment]
thank you I am closing issue
