### ISSUE TITLE
addCustomHostMapping

### ISSUE THREAD

**Issue by RakeshMondalRon** [bseltz-cohesity/scripts#21]
addCustomHostMapping

Hello Brian,

-Is it possible to have list of IP's and host associated with it deleted ?
Os 
-Have the IP address changed for a Host name ?

**Comment by bseltz-cohesity** [comment]
Sure, I will work on it...

**Comment by bseltz-cohesity** [comment]
I added a -delete parameter. It will delete the specified IP(s) from the list of host mappings. To change the IP address of a host, simply add the new IP/Host mapping and then delete the old IP using the -delete parameter. If this doesn't address your requirements, please let me know. https://github.com/bseltz-cohesity/scripts/tree/master/powershell/addCustomHostMapping

**Comment by RakeshMondalRon** [comment]
Hello Brian, Thanks a ton for the -delete Option. Both Delete and Replace IP has it own advantage and Disadvantage, and its own use cases. i'll put it through my testing env and let you know if delete alone would do. Also I would to point out again ,  that "-Backup" option which was added last time is the gold standard and proven winner  many times. ( saving human errors ).
