### ISSUE TITLE
Support for SQL Server Marked Transactions

### ISSUE THREAD

**Issue by ppejovic** [bseltz-cohesity/scripts#22]
To recover Microsoft's Azure DevOps Server you need to restore multiple SQL Server databases to a logically consistent point. This is achieved through the use of [Marked Transactions](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/use-marked-transactions-to-recover-related-databases-consistently?view=sql-server-2016) during the backup and [restore ](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/recovery-of-related-databases-that-contain-marked-transaction?view=sql-server-2016)process. 

During the backup we can potentially execute the transaction mark using a protection group pre-script but it doesn't look like there is any way to instruct Cohesity through the api to restore logs up to a specific transaction mark, much like using `-logTime` in the `restoreSQL` scripts as a point-in-time recovery point.

Are transaction marks supported at all by Cohesity and if not are there any alternatives to achieve logical consistency across multiple databases?

This does feel like more of a support request so I'm happy to close this and direct it to the correct channel. This query just arose from seeing what is available using the restore scripts you've provided. Thanks.

**Comment by bseltz-cohesity** [comment]
I don't believe we have specific support for restoring the logs to a transaction mark in the UI workflow, but we do support resume recovery, where you can restore a database with NORECOVERY and repeatedly restore more logs. I suppose you could then execute the final recovery to the transaction mark from the SQL side? It may require a SQL side script to perform the log restore (not sure, I'm not familiar with transaction marks). If you need help establishing such a workflow, please reach out to your Cohesity account team and they will bring the SQL experts into the conversation.

**Comment by ppejovic** [comment]
Thanks for the reply Brian, the info is very helpful. The resume recovery approach seems like it might be workable so I'll take a look and will follow-up with the account team as you suggested.
