### ISSUE TITLE
WEB URI request to download now working

### ISSUE THREAD

**Issue by manojmittalcohesity** [bseltz-cohesity/scripts#23]
@bseltz-cohesity : The following web-uri request to download script is not working. This is for latestsqlrecoverypoint.ps1 script. Needs correction:

(Invoke-WebRequest -Uri "$repoUrl/$scriptName/$scriptName.ps1").content | Out-File "$scriptName.ps1"; (Get-Content "$scriptName.ps1") | Set-Content "$scriptName.ps1"

**Comment by bseltz-cohesity** [comment]
Fixed!
