### ISSUE TITLE
VFAT filesystems abort Instant Volume Mount

### ISSUE THREAD

**Issue by dragongeek** [bseltz-cohesity/scripts#25]
On my RHEL 8.x server when I run the Instant Volume Mount, it aborts with a complaint that Cohesity cannot handle the VFAT filesystems mounted on /boot/efi. I really appreciate this code, but I'm completely new to Python and the Cohesity API and don't know enough to have it either allow me to specify which mount points (from my RHEL VMware Image with multiple VMDKs), or have it test and ignore any mount points it cannot mount, like this VFAT. The specific error from the Recovery Details is:

Volume /boot/efi with filesystem vfat is not supported

**Comment by bseltz-cohesity** [comment]
Hi @dragongeek I will add an option to specify the volumes that you want to mount. I'll work on this ASAP.

**Comment by bseltz-cohesity** [comment]
I have added a -m (--volume) parameter so you can specify the volume you want to mount like -m / or if you want to mount multiple volumes, you can repeat the parameter like -m / -m /u01
