### ISSUE TITLE
API v2 not available

### ISSUE THREAD

**Issue by Lioxxs** [bseltz-cohesity/scripts#27]
Hi it's a very good job !!!
Some of script are based on API v2, seems that the API v2 is not available by default on cohesity cluster, how to get it please?
regards.

**Comment by bseltz-cohesity** [comment]
Hi @Lioxxs to get v2 API, upgrade your Cohesity cluster to 6.5.1. v2 API was introduced in Cohesity 6.4 and is commonly used in Cohesity 6.5.1 which is a long-term support (LTS) release. I've started using v2 in my scripts that support new Cohesity features that are available in 6.5.1. Older versions of Cohesity such as 6.3.1 do not have v2 API.
