### ISSUE TITLE
Non-deterministic sorting of vmDocuments in restoreSQLDBs.ps1 causes unpredictable restores

### ISSUE THREAD

**Issue by ppejovic** [bseltz-cohesity/scripts#30]
The code referenced below first sorts the `$dbresults` (`vmDocuments`) by `snapshotTimestampUsecs` descending across all databases, then on line 66 sorts that result by `objectName`. The problem here is that the second sort does not predictably retain the ordering of `vmDocument`s by `snapshotTimestampUsecs`.

https://github.com/bseltz-cohesity/scripts/blob/c85f052b04272ccf7ff987d01e0ada13b5f4e1d6/powershell/restoreSQLDBs/restoreSQLDBs.ps1#L65-L66

This can result in strange behaviour where the `vmDocument` you get for a database can be for an old job and may not necessarily have any versions within the log time window (or the last 3 days when using the `-latest` switch).

**Comment by bseltz-cohesity** [comment]
Thanks I have implemented the fix.

**Comment by ppejovic** [comment]
Thanks @bseltz-cohesity. Just a quick question, what are the differences between/use cases for the scripts in `sql-scripts` vs the ones under `powershell`?
