### ISSUE TITLE
Policy to Protected Object Mapping Query

### ISSUE THREAD

**Issue by john-morton** [bseltz-cohesity/scripts#33]
Brian,

My apologies in advance as this is a Feature Request for your policyList.ps1 file (or a file like it) and not an Issue per se.

I am trying to generate a tabular report of Protected Objects (virtual machines) that are protected by a given Policy (not a Protection Job).

For example: Policy 'Gold' protects 'VM1', 'VM2' etc (and not Policy 'Gold' protects 'Job1', which in turn protects 'VM1','VM2' etc).

I've taken a look at (and run) several of your scripts but this is the closest I can find...

Is this possible (and, if so, would you be willing to modify this script such that it might)?

Kind regards,

John

**Comment by bseltz-cohesity** [comment]
Hi John,

This script will generate a CSV including Job Name, Job Type, Policy Name and Object Name: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/jobObjects

Hope that helps!

**Comment by john-morton** [comment]
Aha!

You sir, are a legend!

I dismissed the console output for jobObjects as it only contained the Protection Job and associated Protected Objects.

But, as you rightly point out, the .CSV file has exactly what I need (the Policy as well).

I appreciate you taking the time to point this out. Thanks!

Kind regards,

John
