### ISSUE TITLE
latestSQLRecoveryPoint not working

### ISSUE THREAD

**Issue by TheLowox** [bseltz-cohesity/scripts#35]
The Script is missing the Part:

`
### source the cohesity-api helper code
. $(Join-Path -Path $PSScriptRoot -ChildPath cohesity-api.ps1)
`

Therefore the functions are unknown and the script fails to execute:
![image](https://user-images.githubusercontent.com/79460642/135242279-bddc9a60-438f-45d7-a8b0-a6fbfe3a8b93.png)

**Comment by bseltz-cohesity** [comment]
The download instructions are in the README, but what you need is a copy of the cohesity-api.ps1 library. It is here: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/cohesity-api

**Comment by TheLowox** [comment]
@bseltz-cohesity 

Look at your code, please.
The lines for the library import and also the api authentification are missing.
Once I manually added them it´s working fine.
