### ISSUE TITLE
archiveOldSnapshots Feature Request - Specific Snapshots Only

### ISSUE THREAD

**Issue by dude0404** [bseltz-cohesity/scripts#38]
hi,

first of all thank you very much for your work here, i commonly use these scripts to automate and extend functionality.

i'm looking to archive snapshots taken on a specific day/days. e.g. on the 10th day of the month i wish to archive snapshots taken on the 1st day of the month to <archive target>

could you please consider adding this functionality to archiveOldSnapshots so that rather than archiving all unexpired snapshots there is the option to specify a date or date range of desired snapshots for archival.

thank you

**Comment by bseltz-cohesity** [comment]
Hi dude0404, there's another script that fits your use case, here: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/archiveNow

**Comment by dude0404** [comment]
thanks @bseltz-cohesity
