### ISSUE TITLE
viewDR66 doesn't failover the views and Shares

### ISSUE THREAD

**Issue by DaveHarroldPDS** [bseltz-cohesity/scripts#39]
I am attempting to test the vewiDR66 scripts and the views are not failing over.  I've used the gflags script to set the required gflag.  It viewDR.ps1 script seems to get to the list of views, but doesn't actually process any view.

**Comment by DaveHarroldPDS** [comment]
PS C:\scripts\cohesity-gflags> .\get_gflags.ps1
Connected!

iris:
    multitenancy_guardrail_enabled: true (MaybeEnableGuardrail: Force enabling guardrail via code as MT is disabled)

bridge:
    bridge_apollo_action_executor_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)
    bridge_enable_nas_dr_orchestrator: true (Enable ViewDR)

newscribe:
    scribe_bucket_scan_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)

icebox:
    bridge_apollo_action_executor_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)

cohesity-01 gflags saved to gflags-cohesity-01.csv

Connected!

iris:
    multitenancy_guardrail_enabled: true (MaybeEnableGuardrail: Force enabling guardrail via code as MT is disabled)

bridge:
    bridge_apollo_action_executor_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)
    bridge_enable_nas_dr_orchestrator: true (Enable ViewDR)

newscribe:
    scribe_bucket_scan_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)

icebox:
    bridge_apollo_action_executor_rate_ppm: 660000 (Auto set by Cohesity. Don't update manually.)

cohesity-02 gflags saved to gflags-cohesity-02.csv

PS C:\scripts\cohesity-gflags>

PS C:\scripts\viewdr66> .\1-plannedFailoverPrep.ps1
Connected!

Processing Views
PS C:\scripts\viewdr66>

**Comment by bseltz-cohesity** [comment]
Hi Dave, sorry but the underlying orchestration that the ViewDR66 scripts use is not released yet. In the mean time, please use the ViewDR651 scripts.
