### ISSUE TITLE
REst API EXPORT CONFIG

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#4]
so time ago I did open a call with support on how via Cohesity I could export cluster config and quickly import it if needed.

They said that Cohesity does not provide that option although I see that this is possible via rest api.

I tried it via rest api powershell although I do receive error :

Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.

Tried to run a catch on it but could not find anything.

Any hint on how this would work ?

**Comment by bseltz-cohesity** [comment]
#get
$cluster = api get cluster
#put
api put cluster $cluster
