### ISSUE TITLE
Clonebackuptoview - Output of original file location path

### ISSUE THREAD

**Issue by baggyrick** [bseltz-cohesity/scripts#42]
Not sure where to post comments/requests , sorry.    Is it possible to have a text file alongside the clones backup files which has the full original path of the file ?   I am cloning the backups of SQL database files to a view  but it  would be really useful if the original path was available in some form, this would be so the file could be put back manually in order to start up SQL server where the files were on shared storage, but where the SQL backup was file based not volume based.

**Comment by bseltz-cohesity** [comment]
Hi @baggyrick it would be difficult to deposit the paths onto the view, but what you can do is use this script: https://github.com/bseltz-cohesity/scripts/tree/master/sql/restoreSQL there is a -showPaths option that will show you the original paths of the database and log files of the protected DB.
