### ISSUE TITLE
recoverVM2 needs a network, even if the network is detached 

### ISSUE THREAD

**Issue by ProfDrToast** [bseltz-cohesity/scripts#44]
First of all, thank you for this repo!

Although I call recovervm2 with the -x switch, it still asks for a network.
This is a bit annoying.

**Comment by ProfDrToast** [comment]
when you are at it too, when restoring a vm that has multiple NICs on different networks, you can only select one network which will be applied to all NICs

**Comment by bseltz-cohesity** [comment]
The script has been updated to no longer require a network name if -x is used. The multi-NIC feature will have to wait for some pending API changes. I will update the script again at that time.
