### ISSUE TITLE
runid in the filesearch script

### ISSUE THREAD

**Issue by saravadi** [bseltz-cohesity/scripts#49]
Is it possible to add runid in the filesearch script 

Script Name: restoreFiles.py

**Comment by bseltz-cohesity** [comment]
Hi @saravadi restoreFiles.py already has a --runid parameter

**Comment by saravadi** [comment]
when i use ./fileSearch.py -v cohesity_cluster -u username -p filename its listing the Protection group, Source Server and Filename but not the RUNID
