### ISSUE TITLE
setprotection job

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#5]
Hello Brian,

First of all for all your work in here I would love to learn from you some of REST API.

Since in Cohesity there is still not Exclusion time for certain days in GUI and I have a business case to do so. I am trying to change all starting times of all Jobs with a specific name.

But first I need to get working just for one Job so I could work on it next.

current starting time for those jobs are 3 am I would like to change it to 6 am for just one day and then change it back next day.

So all settings except time should stay as it is.

I did use your code for newprotection job and rest api code from the cluster to create simpliest possible code for me.

Although After I run it powershell freeze and only option is to close it and reopen.

Code below :

$startTime = "06:00"

$hours, $minutes = $startTime.split(':')
if(! $hours -and $minutes){
    Write-Warning "invalid start time"
    exit
}

$setJob = @{

  'startTime' = @{
        'hour' = [int]$hours;
        'minute' = [int]$minutes;
        'second' = 0
 
  
}
}

api post protectionJobs/{185240} $setJob

**Comment by bseltz-cohesity** [comment]
Hi komorek88,

The process is: get the job, change the job properties, then put the job back, like this:

$job = api get protectionJobs/7
$job.startTime.hour = 23
$job.startTime.minute = 00
api put protectionJobs/7 $job

**Comment by komorek88** [comment]
Thank you so much No I changed all in one time good man !
