### ISSUE TITLE
when i use ./fileSearch.py -v cohesity_cluster -u username -p filename its listing the Protection group, Source Server and Filename but not the RUNID

### ISSUE THREAD

**Issue by saravadi** [bseltz-cohesity/scripts#50]
Sorry i did not gave correct statement in before issue. 

when i use ./fileSearch.py -v cohesity_cluster -u username -p filename its listing the Protection group, Source Server and Filename but not the RUNID, if i able to get the runid in the output it would be great. 

_Originally posted by @saravadi in https://github.com/bseltz-cohesity/scripts/issues/49#issuecomment-1090418483_

**Comment by bseltz-cohesity** [comment]
Ah OK. Sorry but RUNID is not a property that can be retrieved from the search.
