### ISSUE TITLE
restoreFiles.py when we provide runid its not working- Error as  Job run xxxx not found

### ISSUE THREAD

**Issue by saravadi** [bseltz-cohesity/scripts#51]
I'm trying to get the particular file to restore, So i'm checking the backedUpFileList-multi.py script to check the runid, but it retrun multiple runid which as the files.

when i tried to use that runid for restore its show Job run not found.

when i do in GUI i can pick any recovery point to do the restore it works fine.

**Comment by saravadi** [comment]
If i run same restoreFiles.py script after some time with same runid its working fine. I felt something is breaking, could you please check it.

**Comment by bseltz-cohesity** [comment]
@saravadi I'm testing and it's working correctly for me. Can you provide the command line options and output that you're seeing?
