### ISSUE TITLE
Clarification how to use with helios API key

### ISSUE THREAD

**Issue by ped998** [bseltz-cohesity/scripts#52]
Can the documentation be clarified on how to use Helios API key for python scripts?

They are working directly to cohesity cluster with -v <cohesity_host> -u <user_name> syntax
I am able to get an authentication with the api key with the flag -i or -k (depending on script) and -v helios.cohesity.com, but I do not see how to specify the cluster.

If this is still "functionality in progress", please let me know.   Thanks.

**Comment by bseltz-cohesity** [comment]
Hi @ped998 support for Helios and API Keys is fully integrated in the scripting libraries, however many scripts were published before these features were available, so we are updating them upon request. Just let us know which scripts you want to use with Helios and we'll get them updated.

**Comment by ped998** [comment]
restoreFiles.py, restoreVMFiles.py and the oracle scripts.  Thanks.

**Comment by bseltz-cohesity** [comment]
restoreFiles.py has been updated to support Helios and API keys: https://github.com/bseltz-cohesity/scripts/tree/master/python/restoreFiles simply use -c <clustername> instead of -v <clustername> and enter the API key when prompted for a password. I will continue to work on these.

**Comment by ped998** [comment]
restoreFiles.py worked as expected - I will look for the others, 

I see what I need to do to fit this into some of my own scripts as well.

**Comment by bseltz-cohesity** [comment]
restoreVMFiles.py has been updated to support Helios.

**Comment by bseltz-cohesity** [comment]
backupNow.py, cloneOracle.py and destroyClone.py have been updated to support Helios, a few more still to do

**Comment by bseltz-cohesity** [comment]
All of the oracle python scripts have been updated to support Helios
