### ISSUE TITLE
registeredSources.py when does not have connection

### ISSUE THREAD

**Issue by saravadi** [bseltz-cohesity/scripts#54]
Hi Brian,

  When i try to get the list of register source from cohesity, if host does not have connection  i'm getting below error, can it fixed with status no connection instead getting below errors?
 
('Connection aborted.', error(113, 'No route to host'))
Not Connected
Not Connected
Traceback (most recent call last):
  File "./registeredSources.py", line 37, in <module>
    for source in sorted(sources['rootNodes'], key=lambda node: node['rootNode']['name']):  # sorted(searchResults, key=lambda result: result['vmDocument']['versions'][0]['snapshotTimestampUsecs'], reverse=True)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by bseltz-cohesity** [comment]
Fixed: https://github.com/bseltz-cohesity/scripts/tree/master/reports/python/registeredSources
