### ISSUE TITLE
-useApiKey

### ISSUE THREAD

**Issue by davidsig** [bseltz-cohesity/scripts#59]
Hi can you add support for api key authentication for restoreOracle.ps1 and parallel-process-mssql-objects.ps1 ?

**Comment by bseltz-cohesity** [comment]
I just added API support to restoreOracle.ps1. I'm not familiar with the script parallel-process-mssql-objects.ps1. Did you rename the script, and if so, let me know the original script name?

**Comment by davidsig** [comment]
Thank you!
the other script I was refering to is in another repo:
bseltz-cohesity/cohesity-powershell-module/samples/RestoreSQLDB/parallel-process-mssql-objects.ps1

**Comment by davidsig** [comment]
Brilliant, thank you.
I will take a look at this :)
