### ISSUE TITLE
edit protectionpolicy

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#6]
Hello Brian,

Thank again for that tip.
This task now which I need help on is still about same script I did that all my jobs with specific name can temporary run on different time.
Although would like to now work out how in the same time use same same regarding slighly adjust blackout window.

I am trying like that .

$policies = api get protectionPolicies/3470062840085312:1554112082174:4717
$policies.blackoutPeriods.endtime{
hour = 05
}

but not sure how to edit endtime hour of blackout to then run 

api put protectionJobs/3470062840085312:1554112082174:4717 $policies

Could you please assist Brian?

**Comment by komorek88** [comment]
not sure how to catch it if I want to change just for one day

 C:\> $policies.blackoutPeriods |fl


day       : kSaturday
startTime : @{hour=23; minute=0}
endTime   : @{hour=0; minute=0}

day       : kSunday
startTime : @{hour=0; minute=0}
endTime   : @{hour=3; minute=0}

day       : kWednesday
startTime : @{hour=21; minute=30}
endTime   : @{hour=0; minute=0}

day       : kThursday
startTime : @{hour=0; minute=0}
endTime   : @{hour=6; minute=0}

**Comment by komorek88** [comment]
ok cracked it please close it :

$policies = api get protectionPolicies/3470062840085312:1554112082174:4717
$sunday = $policies.blackoutPeriods |? {$_.day -eq "kSunday"}
$sunday.endTime.hour = 3
$idsunday = $policies.id
api put protectionPolicies/$idsunday $policies

**Comment by bseltz-cohesity** [comment]
Exactly! Now you are learning it!!

**Comment by komorek88** [comment]
Finished I've created script which change onetime schedule for all jobs from particular region of my organization. on top of it it adjust black out window for them. business reason was Month End  for finance to not affect on their sql backup performance. REST API is cool ! thank for your template it became so easy now. So far Cohesity GUI does not have day exclusion in GUI to run jobs at different time for particular day. So that was work around.

Thanks again !

Next will focus on jobs with Warning Status as those are counted bu Cohesity GUI / Report as Success not Fail. Although when you backup Exchange and logs are not truncated for servers it counts it as Warning but should be as Failed as disk drives get overloaded with logs.

Will contact you back if will stuck on something
