### ISSUE TITLE
Helios Auth with API key and execute on local cluster

### ISSUE THREAD

**Issue by ziptx** [bseltz-cohesity/scripts#60]
Would you be willing to provide some clarity on your 'Authentication Explained' Wiki on how to execute a powershell report command [such as /reports/powershell/backupSummaryReport] through Helios to the selected cluster.

The examples are clear to:
Authenticate to Helios in PowerShell:
```powershell
apiauth -helios
```
When prompted for your password, paste the API key and press enter. 
Then select which cluster to use:
```powerShell
heliosCluster Cluster-01
```

What is unclear is how to pass this Helios authentication through to the powershell reporting script.    The script wants VIP etc, when the assumption of -helios or -useApiKey should derive the details from the above authentication.   What is the correct way to 'proxy' that powershell script through Helios to the local\selected cluster?

**Comment by bseltz-cohesity** [comment]
@ziptx I have updated the doc with new sections: https://github.com/bseltz-cohesity/scripts/wiki/Authentication-Explained#selecting-a-helios-connected-cluster-to-work-with and https://github.com/bseltz-cohesity/scripts/wiki/Authentication-Explained#selecting-a-helios-connected-cluster-to-work-with and I've also updated the backupSummaryReport https://github.com/bseltz-cohesity/scripts/tree/master/reports/powershell/backupSummaryReport
