### ISSUE TITLE
trying to register an uda source fails if there are two hostnames/fqdn in the argumentlist -sourcename

### ISSUE THREAD

**Issue by gerardiro** [bseltz-cohesity/scripts#63]
trying to register an uda source fails if there are two hostnames/fqdn in the argumentlist -sourcename

it is possible to add an uda source name that has 2 fqdn/hostnames. but if we try to add such source with the command it fails:

Connected!
Registering UDA protection source '$clientvirtuname, $clientphyname'...
Failed to connect to $clientvirtuname, $clientphyname. Error: Cohesity service on host $clientvirtuname, $clientphyname cannot be reached. Please confirm Cohesity Agent is install
ed successfully on the host, check connectivity to the service, including the required ports, firewall rules, the service status, and the permissions for the service logon account
.. Connectivity status: Connection to $clientvirtuname, $clientphyname:50051 resulted in : Failed to resolve server name with error: System error

**Comment by bseltz-cohesity** [comment]
@gerardiro  thanks for the feedback. The script has been updated.
