### ISSUE TITLE
if multiple objects are added to the protection group, they are not added correctly

### ISSUE THREAD

**Issue by gerardiro** [bseltz-cohesity/scripts#64]
during the configuration of the protection job using the gui, it is possible to add more then one object
![image](https://user-images.githubusercontent.com/103168860/175018161-876dbb6b-749a-43bd-b16c-f4ff8c2641dd.png)

we are unable to add more then one object if we use the script as the optional variable interpreted the coma separated as one:
-objectName $db.OBJECTS `
where PS D:\cohesity\Automation\registerUDA> $db.OBJECTS
SYSTEMDB,INVENTORY,ABC

**Comment by bseltz-cohesity** [comment]
@gerardiro it looks to me that $db.OBJECTS is a string, not a list. `-objectName` expects a list. So you need to convert $db.OBJECTS to a lists, like:
```
-objectName @($db.OBJECTS -split ',')
```

**Comment by gerardiro** [comment]
great hint! thank you very much @bseltz-cohesity  it worked like a charm:
![image](https://user-images.githubusercontent.com/103168860/175022851-5c75d576-ae0f-4c47-800d-a42df88c8bb8.png)

thank you very much for the quick response and suggestion, always highly appreciated!
