### ISSUE TITLE
protectSQLServer Error 'objects' cannot be found on this object

### ISSUE THREAD

**Issue by jesseschaal** [bseltz-cohesity/scripts#65]
Trying to add SQL servers to our existing protection group. Here is what i am getting:

CODE:
# example
./protectSQLServer.ps1 -vip omaccohcls00.mutualofomaha.com `
                       -username ansible `
                       -domain LOCAL `
                       -servername wn3336.corp.com `
                       -jobname 'SQL - 2017 - WN2294 - Jesse'
# end example

PS C:\Scripts\Cohesity> # example
./protectSQLServer.ps1 -vip omaccohcls00.com `
                       -username ansible `
                       -domain LOCAL `
                       -servername wn3336.corp.com `
                       -jobname 'SQL - 2017 - WN2294 - Jesse'
# end example
Connected!
Updating job SQL - 2017 - WN2294 - Jesse...
The property 'objects' cannot be found on this object. Verify that the property exists and can be set.
At C:\Scripts\Cohesity\protectSQLServer.ps1:237 char:9
+         $params.objects = @($params.objects + @{ 'id' = $serverSource ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
Protecting wn3336.corp.com...
[13]:Error occurred while fetching summary of Protection Groups: An internal component may be down.

Able to add the server manually to the PG. thank you in advance.

**Comment by bseltz-cohesity** [comment]
Hi @jesseschaal please get the latest version of the script here: https://github.com/bseltz-cohesity/scripts/tree/master/sql/protectSQLServer and try it again. There was a bug in an older version
