### ISSUE TITLE
restoreSQL.ps1 - restore location of mdf file

### ISSUE THREAD

**Issue by waghbakri** [bseltz-cohesity/scripts#68]
Using below command to restore a database.

_restoreSQL.ps1 -vip xxxyyyzzz.abc.com -username xxx -domain xxxx -sourceServer prodServer1 -sourceDB "DB1" -targetServer devServer1 -targetInstance "INST1" -targetDB "DB1_bak" -mdfFolder 'D:\Program Files\Microsoft SQL Server\MSSQL12.INST1\MSSQL\DATA' -ldfFolder 'E:\Program Files\Microsoft SQL Server\MSSQL12.INST1\MSSQL\TLog' -ndfFolder 'X:\Program Files\Microsoft SQL Server\MSSQL12.INST1\MSSQL\DATA' -useApiKey -password xxxxxx -progress -overwrite_

After the restore completes the mdf file is located on drive X as opposed to drive D.

**Comment by bseltz-cohesity** [comment]
Please use the `-ndfFolders` parameter (not the -ndfFolder parameter) as described here: https://github.com/bseltz-cohesity/scripts/tree/master/sql/restoreSQL#multiple-folders-for-secondary-ndf-files this will allow you to place specific ndf files in different locations
