### ISSUE TITLE
REQ: Support for two oder more cohesitys in different Datacenters

### ISSUE THREAD

**Issue by HenrikFFM** [bseltz-cohesity/scripts#69]
If you have 2 Cohesitys in different datacenters. i may need some time to transfer large backups from one datacenter to another.
But you can start a restore only after the replication is complete.

Plz add support for this..

We want to create an restore Job für dev/test that starts if the replication is ready. 
I want to ask for the replication status and if it finishes the restore should start, thsi ist because i cant calculate the time the replication is needed.

**Comment by bseltz-cohesity** [comment]
Hi @HenrikFFM what restore script are you referring to?

**Comment by HenrikFFM** [comment]
SQL Server at first. 
Later than Oracle.

We have a production datacenter and one for dev/uat.

**Comment by bseltz-cohesity** [comment]
As this is a new feature request, please contact your Cohesity sales team to have your request submitted.
