### ISSUE TITLE
warning auto email

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#7]
Hi Brian,

As you aware Cohesity counts Warning job with kSuccess.
Although I found a way to distinguish that.

But now my question is how I can run a script to autologin to restapi without my typing in a password. Best would not save that password anyway. Perhaps local admin password shoul be used but this would be against security to save it anywhere locally.

My idea would be to to somehow place it on actual cluster but maybe you have better ideas.

My script is ;

$run = api get protectionRuns | ? {($_.backuprun -match "warnings")} 

$data = foreach ($single in $run) {

$single.jobname 

""

$single.backuprun.warnings

""

} 

$Message = "<html><head></head><body><p>Jobs with Warning Status :</br></br></br></br>$data</br>
</p></body></html>"

$datamsg = [string]$data

Send-MailMessage ......

**Comment by komorek88** [comment]
in $MEssage part I have html code that is why it is looking wierd

**Comment by bseltz-cohesity** [comment]
```
$runs = api get "protectionRuns?startTimeUsecs=$(timeAgo 24 hours)" | Where-Object {$_.backupRun.sourceBackupStatus.warnings -ne $null}

foreach ($run in $runs){
    foreach($source in $run.backupRun.sourceBackupStatus){
        if($source.PSObject.Properties['warnings']){
            "{0} - {1} - {2}" -f $run.jobName, $source.source.name, $source.warnings[0]
        }
    }
}
```

**Comment by komorek88** [comment]
That is nice Output Thanks, but how I can auto schedule it as email.
If I need to save password somewhere is OK but best would be to not send anywhere and run it in schedule.

Any ideas?

**Comment by bseltz-cohesity** [comment]
The apiauth function in cohesity-api.ps1 has never had a password input parameter. It prompts you once to enter your password and it stores it encrypted for later use so that your scripts can run unattended. It has never been necessary to hard code your password in a script.

**Comment by komorek88** [comment]
worked but still had to save password for email account which sends email from :
when used::
Send-MailMessage

But thanks at least is working just not fully secure.

Maybe at some stage Cohesity will improve that so could be set as a autoscheduled report in GUI
