### ISSUE TITLE
restoreSQL.ps

### ISSUE THREAD

**Issue by HenrikFFM** [bseltz-cohesity/scripts#72]
I start restoreSQL.ps1 as SQL Server Agent Powershell Step:

And an error message like 

The remote name could not be resolved: 'xxx-xxx-xxxx.xxx-cloud.local'

appears not in the sql server agent log but only in the cohesity-api-debug.log

Is this a bug, a feature or by design

**Comment by bseltz-cohesity** [comment]
Hi @HenrikFFM the message suggests that the SQL server can not resolve the name 'xxx-xxx-xxxx.xxx-cloud.local' can you open a command prompt on that SQL server to confirm whether you can nslookup or ping that name?

**Comment by bseltz-cohesity** [comment]
I have updated restoreSQL.ps1 to exit with an error if authentication fails: https://github.com/bseltz-cohesity/scripts/tree/master/sql/restoreSQL
