### ISSUE TITLE
creating a RA protection group with the script does not set the parameters and script location for the full backup

### ISSUE THREAD

**Issue by gerardiro** [bseltz-cohesity/scripts#73]
Hi Brian, 

i hope you are doing well.

We are using the script with the following variables in order to create the RA protection groups for many sap hana DBs:
![image](https://user-images.githubusercontent.com/103168860/178213185-92af21f8-ecee-4da6-9615-56b1dc8f66c7.png)

the protection group was created successfully, however the following attributes are missing:
script information for full schedule:
- scripts path
- parameters
![image](https://user-images.githubusercontent.com/103168860/178213413-d08727cc-60e0-4bff-9d5d-39f441193b45.png)

as far as i can understand the following parameters should configure the full and incremental params and script paths in the protection group:
-scriptPath '/home/oracle/scripts/dbbackup.sh' `
                           -scriptParams 'my params' `
                           -logScriptPath '/home/oracle/scripts/logbackup.sh' `
                           -logScriptParams 'other params'

unfortunatelly it does not.

**Comment by bseltz-cohesity** [comment]
I've added support for the full backup script and params: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/protectRemoteAdapter

**Comment by gerardiro** [comment]
Hi Brian,

Thanks for the quick reaction. Now it looks very well:
***@***.***

Do you know how I can start the full backup after the protection group has been created, unfortunately the cmdlet Start-CohesityProtectionJob -name $db.ProtectionGroupName -RunType KFull
 Fails with the following error:
Start-CohesityProtectionJob : Error converting value "kUDA" to type 'System.Nullable`1[Cohesity.Model.ProtectionJob+EnvironmentEnum]'. Path '[56].environment', line 1, position
3197830.
At line:1 char:1
+ Start-CohesityProtectionJob -name $db.ProtectionGroupName -RunType KF ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-CohesityProtectionJob], JsonSerializationException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonSerializationException,Cohesity.Powershell.Cmdlets.ProtectionJob.StartCohesityProtectionJob

Thank you in advance!

Best regards,


Gabriel Aleksov
Cloud Operations Engineer

KPMG IT Service
Business Park Sofia
Building 15A, Floor 3
Sofia 1766
Bulgaria

T +49 3020 684 307
M +359 886886822
***@***.******@***.***>
www.kpmg.de<https://home.kpmg.com/de/de/home.html>


P Please consider the environment before printing this e-mail.


Planned vacation:
August 8th – August 12th,
August 22nd – August 26th,
September 5th – September 9th

**Comment by bseltz-cohesity** [comment]
You can use this script to run the job: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/backupNow

```./backupNow.ps1 -vip ve2 -username admin -jobName 'my job' -backupType kFull```

**Comment by gerardiro** [comment]
Great, thank you very much! Works very well!

Best regards,


Gabriel Aleksov
Cloud Operations Engineer

KPMG IT Service
Business Park Sofia
Building 15A, Floor 3
Sofia 1766
Bulgaria

T +49 3020 684 307
M +359 886886822
***@***.******@***.***>
www.kpmg.de<https://home.kpmg.com/de/de/home.html>


P Please consider the environment before printing this e-mail.


Planned vacation:
August 8th – August 12th,
August 22nd – August 26th,
September 5th – September 9th
