### ISSUE TITLE
mountOracleAsView.py has hard-coded destination target

### ISSUE THREAD

**Issue by ped998** [bseltz-cohesity/scripts#75]
I was testing mountOracleAsView.py and saw that it has a hard-coded host-id on line 174 - looks like leftovers for your testing.

Your script uses the v2 api, which looks much simpler than what I wrote for using the /recoverApplication v1 api.

I may be doing some tests trying to build an "instant recover" script for Oracle (also using v2 data-protect/recoveries).   If I get something that works, I will pass it on.

Thanks.

**Comment by bseltz-cohesity** [comment]
Fixed. Thanks for finding that.
