### ISSUE TITLE
In-memory enabled SQL DB restore fails

### ISSUE THREAD

**Issue by waghbakri** [bseltz-cohesity/scripts#76]
In-memory enabled SQL DB restore to a different host fails. 

Specified these Data/Log/Secondary file locations in the GUI:

> Data File Destination: W:\Program Files\Microsoft SQL Server\MSSQLvv._instancename_\MSSQL\DATA
> Secondary Data File Destination:
> “.*InMemory” to “W:\Program Files\Microsoft SQL Server\MSSQLvv._instancename_\MSSQL\DATA”
> Overwrite Alternate Database: Yes
> Log File Destination: E:\Program Files\Microsoft SQL Server\MSSQLvv._instancename_\MSSQL\DATA
> Instance Name: _instancename_

Attempt failed with below error:

> Error [kVSSError]: The file "*" already exists in the specified destination directory "W:\Program Files\Microsoft SQL Server\MSSQLvv._instancename_\MSSQL\DATA\InMemory", but overwriting files is not permitted for component "Component: [path='_servername_\\_instancename_', name='_databasename_', is_selectable='false']" in writer "SqlServerWriter". Supply a different destination directory.

**Comment by bseltz-cohesity** [comment]
Please open a support case, our SQL experts can determine the issue.
