### ISSUE TITLE
M365 large scale

### ISSUE THREAD

**Issue by burnziii** [bseltz-cohesity/scripts#79]
When using script to protect mailboxes at this wiki page it is mentioned that each protection group should contain max 5000 objects (https://github.com/bseltz-cohesity/scripts/wiki/Protecting-O365-Objects).

Is the flag "-allMailboxes" choosing only 5000 or do I have to put a list with 5000 and at the next run there will be the next 5000 objects added automatically while choosing "-allMailboxes"?

**Comment by bseltz-cohesity** [comment]
Correct, the -allMailboxes switch will add mailboxes to a protection group until the number of mailboxes in that job is equal to -maxMailboxesPerJob which is by default 5000. If you have more mailboxes than that you can run the script again with a different protection group name,  and the next group of up to 5000 mailboxes, and so on.

**Comment by burnziii** [comment]
Great, thank you very much for your quick response.
Would be great if these "limits" for m365 scaling would be mentioned in the offical documentation.
