### ISSUE TITLE
smb file open by ?

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#8]
Hello Brian,

Thank again you doing great job here.

 I do not see in REST API option to see who have open which files of the view currently.
Handy option when moving shares to know if somebody is actually using it now.

I iris_cli I usually use :

view list-smb-file-opens name=(viewname)

How can I work on with it in RES API ?

**Comment by bseltz-cohesity** [comment]
`api get smbFileOpens?viewName=scripts`
You can find the documentation on this api call at `https://{yourcluster}/docs/restApiDocs/browse/`

**Comment by komorek88** [comment]
I will open support call about this it is not working for me

**Comment by komorek88** [comment]
FYI Case number = 00130080
