### ISSUE TITLE
restoreSQL.ps script from SQL Server Agent job

### ISSUE THREAD

**Issue by tsarp** [bseltz-cohesity/scripts#80]
Hey Brian,

I have SQL Server agent job which restores databases from Cohesity on a daily basis by using powershell. I use cohesity-api.ps and restoreSQL.ps.
When I run the job I have got an error that says it is trying to get the password from prompt which is not possible in an agent job.
When I run the same script with -nopromt parameter it doesn't trigger the restores.
When I add -nopromt = $true to the restoresql.ps file, it doesn't trigger the restores again.
The only way I could run this process successfully is hardcoding the user's password into the code I am calling from agent job.

I wonder if there is another workaround for this. 

Thank you.

**Comment by bseltz-cohesity** [comment]
Hi @tsarp please make sure you have the latest version of both restoreSQL.ps1 and cohesity-api.ps1 and then you can include `-password mypassword` on the command line. After the job has run once, the password will be stored encrypted in the user's registry, and you can remove the `-password mypassword` from the command line.

Alternatively, if you can remote desktop into the SQL server `using the SQL Agent service account`, you can just open powershell and run the restoreSQL.ps1 command by hand and let it prompt you for the password, and the password will be stored.

**Comment by tsarp** [comment]
Thank you for your answer Brian, I successfully managed to run the scripts from SQL Server agent job on my test environment. Now I am going to deploy the solution on my prod environment. I am closing the issue. 
Cheers
