### ISSUE TITLE
REQ:  Icebox / Archival Job State

### ISSUE THREAD

**Issue by ziptx** [bseltz-cohesity/scripts#81]
Appreciate all the knowledge in these scripts.  Hard to put a price on the value you've created.   

I cannot locate anything that references pulling "Archival Jobs" and their "Job State".   Is there a current script that references pulling Archival Task Activity?  We typically pull data through Helios from all the connected clusters.

Siren has this data at Remote Proxy page > Bridge > icebox > Icebox Master Location > "Archival Jobs" (kArchivingBlobs) section.

**Comment by bseltz-cohesity** [comment]
Glad you find the scripts useful. I have the following scripts related to archival reporting:

- Helios protection activity report (shows local, replica and archival activities): https://github.com/bseltz-cohesity/scripts/tree/master/reports/heliosV2/powershell/heliosProtectionActivitiesReport
- Archived Objects Report: https://github.com/bseltz-cohesity/scripts/tree/master/reports/powershell/archivedObjects
- Archive Queue: https://github.com/bseltz-cohesity/scripts/tree/master/powershell/archiveQueue
and there are numerous other scripts that start or cancel archives. Let me know if you need anything that these don't cover.

**Comment by ziptx** [comment]
Wow.  Must have been user error in the search ;).  Those are exactly the items I was trying to find in my search.    Sorry for the use of your time on posting this.    Thanks again.
