### ISSUE TITLE
protectLinux.ps1 Issues

### ISSUE THREAD

**Issue by werkkrew** [bseltz-cohesity/scripts#83]
First off, thanks a lot for posting these, they have been an immense help!

In the protectLinux script there is an issue where if you provide a list of servers it tries to create the PG for every server in the list and thus only the first server actually gets added to the PG.

Additionally, if you could add a parameter like exists in the protectWindows script for $allDrives (protect all local volumes checkbox in gui) that would be amazing.

Thanks again!

**Comment by bseltz-cohesity** [comment]
Thanks for finding that issue, I fixed it and I also added a `-allLocalDrives` command line switch.
