### ISSUE TITLE
recoveryPoints show all Archival points

### ISSUE THREAD

**Issue by nwageler** [bseltz-cohesity/scripts#85]
Is it possible to update recoveryPoints.ps1 to show all Archive recovery points if a job is archived to multiple Cloud Archive targets?

Example:
Job Run 11/21/2022
- Archived to 'Cloud Archive Target A'
- Archived to 'Cloud Archive Target B'

Currently recoveryPoints.ps1 only outputs one of the Archive recovery points.

Background, is we are after a complete list of snapshots in all Cloud Archive targets. So if there is another script that would better achieve this, I would also be interested in that.

Thanks!!

**Comment by bseltz-cohesity** [comment]
Done. I had to break out the local and archival copies onto separate lines of the spreadsheet. https://github.com/bseltz-cohesity/scripts/tree/master/reports/powershell/recoveryPoints

**Comment by nwageler** [comment]
Thanks Brian! Confirmed I can see both archive copies now.
