### ISSUE TITLE
backup specific folders

### ISSUE THREAD

**Issue by geoffaskam** [bseltz-cohesity/scripts#87]
Hi, is there a way of backing specific folders (or via wildcard) in a protection group in backupNow or equivalent?

for example a protection group maybe set to backup /disk, within /disk are various sub-folders so would it be feasible to, on occasion, backup / archive some of these but not all. A bit like a restore of specific files?

e.g.
backupNow.py -v cluster name -u userid -j 'Protection Job' -f 'docs scans' -w

where -f might be a flag to specify files and folders?

**Comment by bseltz-cohesity** [comment]
Yes. In the doc https://docs.cohesity.com/6_6/Web/UserGuide/Content/Dashboard/Protection/JobServerPhysical_FileBased.htm#ProtectaPhysicalServerFilebased search for "directive". You can specify a directive file, which contains the paths you want to include in the backup. You can then populate a directive file on the protected server and then call backupNow, specifying the path to the directive file for this backup. Look for the `metadatafile` parameter in the backupNow readme.

**Comment by geoffaskam** [comment]
Thanks Brian, I’ll take a look.

Regards

Geoff Askam

DMS Technical Manager

From: geoffaskam ***@***.***>
Sent: 13 December 2022 09:10
To: bseltz-cohesity/scripts ***@***.***>
Cc: Geoff Askam ***@***.***>; Your activity ***@***.***>
Subject: [EXTERNAL] [bseltz-cohesity/scripts] backup specific folders (Issue #87)


Hi, is there a way of backing specific folders (or via wildcard) in a protection group in backupNow or equivalent?

for example a protection group maybe set to backup /disk, within /disk are various sub-folders so would it be feasible to, on occasion, backup / archive some of these but not all. A bit like a restore of specific files?

e.g.
backupNow.py -v cluster name -u userid -j 'Protection Job' -f 'docs scans' -w

where -f might be a flag to specify files and folders?

**Comment by geoffaskam** [comment]
Appears to work well, thanks Brian (once I’d amended job to also use directive file)

Regards

Geoff Askam

DMS Technical Manager

From: Brian Seltzer ***@***.***>
Sent: 13 December 2022 09:46
To: bseltz-cohesity/scripts ***@***.***>
Cc: Geoff Askam ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [bseltz-cohesity/scripts] backup specific folders (Issue #87)


Yes. In the doc https://docs.cohesity.com/6_6/Web/UserGuide/Content/Dashboard/Protection/JobServerPhysical_FileBased.htm#ProtectaPhysicalServerFilebased<https://docs.cohesity.com/6_6/Web/UserGuide/Content/Dashboard/Protection/JobServerPhysical_FileBased.htm#ProtectaPhysicalServerFilebased> search for "directive". You can specify a directive file, which contains the paths you want to include in the backup. You can then populate a directive file on the protected server and then call backupNow, specifying the path to the directive file for this backup. Look for the metadatafile parameter in the backupNow readme.
