### ISSUE TITLE
timeout on backupNow

### ISSUE THREAD

**Issue by geoffaskam** [bseltz-cohesity/scripts#88]
Hi Brian, 

when running backupNow with latest version I now get the following;

Connected!
Running AIX mb835 Protection Job PDC...
Timed out waiting for new run to appear

I have tried using -nrt but still get this mesage. the percentage complete (now -pr) doesnt show either?

my syntax at command is, generally similar to;

backupNow.py -v clustername -u aix -j 'job name' -nrt 2400 -pr -w

**Comment by bseltz-cohesity** [comment]
Hi Geoff, what version of Cohesity is running on your cluster?
