### ISSUE TITLE
Helios REST API

### ISSUE THREAD

**Issue by komorek88** [bseltz-cohesity/scripts#9]
Hi Brian,

Not sure how to contact with you directly so using this method.

1. Do you have cohesity-api.ps1 way to use Helios REST API ?( it is different method not to get token it is via API)

2. do you have any hint how to use Helios REST API ?

Regards,
Adrian

**Comment by bseltz-cohesity** [comment]
I don't have any info on the Helios API yet. Can you open a support case and let me know the case number. I will follow up internally to chase down the documentation so that I can create some examples.

**Comment by komorek88** [comment]
I did open before I contacted you.
Number is : 00116917

**Comment by komorek88** [comment]
Hi Brian,

Looks like is no use case yet.
As it is still per cluster so not much benefit of it.

Regards,
Adrian

**Comment by komorek88** [comment]
Hi Brian,

Looks like is no use case yet.
As it is still per cluster so not much benefit of it.

Regards,
Adrian

**Comment by komoreka** [comment]
Hello Brian,

I need to use Helios Api Generated key did you manage to find out how to authorize to it I tried few things and I am unable to.

call opened: 00157262

**Comment by bseltz-cohesity** [comment]
I just tried it and I could not successfully authenticate to Helios via the accessTokens API. I'm asking my API team to provide us with a solution.
