### ISSUE TITLE
restoreOracle.py - add support for initOracle parameters containing =

### ISSUE THREAD

**Issue by ped998** [bseltz-cohesity/scripts#91]
Add after line 381:
            if len(paramparts) == 3:
                paramval = paramval+"="+paramparts[2].strip()

**Comment by bseltz-cohesity** [comment]
Updated, thanks

**Comment by ped998** [comment]
As an FYI - for the parameter to work, it must be properly quoted as well - in my example:

-pf tde_configuration="'KEYSTORE_CONFIGURATION=FILE'" -pf wallet_root=+data/MYDB/WALLET

Note the single-quotes inside the double-quotes

**Comment by bseltz-cohesity** [comment]
I have added those examples to the README, thanks
