### ISSUE TITLE
protectView.py jobname error

### ISSUE THREAD

**Issue by amlucent** [bseltz-cohesity/scripts#93]
when I run protectView.py as your example shows with  -j 'my view backup'  -n myview1 -p 'my policy' and I am getting an error

```
 File "/.../protectView/protectView.py", line 96, in <module>
   job = [j for j in (api('get' , 'data-protect/protection-groups?environments=kview', v=2))['protectionGroups'] if j['name'}.lower() == jobname.lower()]
TypeError: 'Nonetype' object is not iterable 
```

Are some of these scripts dependent on https://github.com/cohesity/management-sdk-python?

**Comment by bseltz-cohesity** [comment]
Fixed...

**Comment by amlucent** [comment]
thank you.  That worked.  So I have another ask.  Can I get a --drprefix switch instead of a suffix?  It would just make more sense for my environment

**Comment by bseltz-cohesity** [comment]
Done. I added -prefix, --drprefix
