### ISSUE TITLE
backupNow adherence to policy

### ISSUE THREAD

**Issue by nwageler** [bseltz-cohesity/scripts#94]
We are testing implementation of backupNow to initiate runs for a protection group that is set to paused (to be run on-demand only).

The policy includes Daily local backup, Daily replication and Monthly cloud archive:
![policy](https://user-images.githubusercontent.com/91289520/225681334-e6e82b7b-3731-4fd2-8998-0a093594e156.png)

However running backupNow daily (without any copy retention parameters) always triggers a cloud archive which should only be running Monthly according to the policy:
![runs](https://user-images.githubusercontent.com/91289520/225681327-3752de85-fa33-4e2b-9cc9-c2aedda96a4a.png)

Command syntax used:
```
./backupNow.ps1 -vip mycluster `
                -username myusername `
                -domain mydomain.net `
                -jobName 'My Job'
```

We are not able to make use of the optional copy retention parameters in this case.

Is it possible to have backupNow strictly adhere to the frequency and retention specified in the protection group's policy?

**Comment by bseltz-cohesity** [comment]
I understand the request, but backupNow is designed to be analogous to the run now dialog in the Cohesity UI, which also does not respect the frequency of the remote targets. The reason being that it would be highly complex to calculate whether we need an archive during this run of the script or not, and that would likely lead to unexpected behavior. Instead you can use the `-noArchive` command line switch to stop it from archiving, and on the day of the month you wish to archive, you can omit that switch. Hope that helps!

**Comment by nwageler** [comment]
Makes sense, thank you!
