### ISSUE TITLE
request - python based join LDAP and AD directory scripts?

### ISSUE THREAD

**Issue by amlucent** [bseltz-cohesity/scripts#97]
Im not finding any scripts to join a cohesity cluster to an LDAP or AD domain.  Closest I can find is this https://github.com/bseltz-cohesity/scripts/tree/master/python/onboardADUser.  Would this be something I could request?

I did find this one - https://github.com/bseltz-cohesity/scripts/tree/master/powershell/addActiveDirectory but I lack powershell core on my linux ansible host where I use these but I will pursue that as well.

**Comment by bseltz-cohesity** [comment]
Here you go, just published: https://github.com/bseltz-cohesity/scripts/tree/master/python/joinActiveDirectory
